### ISSUE TITLE
Range randomly jumps between xxx,0 and 0,xxx

### ISSUE THREAD

**Issue by Partovic** [skodaconnect/homeassistant-myskoda#100]
**Describe the bug**
The value of the „Range“ sensor sometimes randomly changes e.g. from 385,0 to 0,385 km. After a while it gets updated back to the correct value.

**Is this working in MySkoda app?***
When this issue occurs. The MySkoda app is still showing the correct value.

**Comment by WebSpider** [comment]
Thanks for reporting this!

We have already noticed this behaviour in #77 and will be fixed in the next release

**Comment by WebSpider** [comment]
This has been fixed in v1.5.0
