### ISSUE TITLE
Poll for new vehicles

### ISSUE THREAD

**Issue by Prior99** [skodaconnect/homeassistant-myskoda#108]
If a vehicle is missing in the initial request for listing vehicles, it will not be added afterwards.

Poll for new vehicles regularly.

**Comment by WebSpider** [comment]
I've had a second look at this, and since this is currently done at integration initialisation, I do not see any reason why we should not simply document that when a new vehicle has been added to the users account, they should reload the integration. It will then be auto-discovered.
