### ISSUE TITLE
mashumaro.exceptions.InvalidFieldValue: Field "positions" of type list[Position] in Positions has invalid value

### ISSUE THREAD

**Issue by Mheel80** [skodaconnect/homeassistant-myskoda#113]
During the integration initialization the following error occurs:

Logger: myskoda.rest_api
Källa: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:376
Inträffade först: 11:42:47 (7 händelser)
Senast loggade: 11:47:24

Failed to deserialize data: {"positions":[{"type":"VEHICLE","gpsCoordinates":{"latitude":55.566278,"longitude":12.980755},"address":{"city":"Malmö","country":"Sweden","countryCode":"SE","street":"Malmö"}}],"errors":[]}
Traceback (most recent call last):
  File "<string>", line 8, in __mashumaro_from_dict_json__
  File "<string>", line 13, in __mashumaro_from_dict_json__
mashumaro.exceptions.MissingField: Field "zip_code" of type str is missing in Address instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 16, in __mashumaro_from_json__
  File "<string>", line 10, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "address" of type Address in Position has invalid value {'city': 'Malmö', 'country': 'Sweden', 'countryCode': 'SE', 'street': 'Malmö'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 18, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "positions" of type list[Position] in Positions has invalid value [{'type': 'VEHICLE', 'gpsCoordinates': {'latitude': 55.566278, 'longitude': 12.980755}, 'address': {'city': 'Malmö', 'country': 'Sweden', 'countryCode': 'SE', 'street': 'Malmö'}}]

**Comment by WebSpider** [comment]
Thanks for your report!
It looks like in your country zipcodes are not always sent, and that's new to us. We'll patch this!

**Comment by minisweed** [comment]
I created a new post before seeing this,

I am getting this error also 

![image](https://github.com/user-attachments/assets/6e2af850-79aa-4f97-a6ea-015870d29528)

Any eta on the update :) no rush
