### ISSUE TITLE
Unhandled exception from <bound method>

### ISSUE THREAD

**Issue by arjanvroege** [skodaconnect/homeassistant-myskoda#122]
**Describe the bug**
Error in HA logs:

This error originated from a custom integration.

Logger: custom_components.myskoda.coordinator
Source: helpers/debounce.py:137
integration: MySkoda (documentation, issues)
First occurred: 22:59:38 (3 occurrences)
Last logged: 23:07:15

Unexpected exception from <bound method MySkodaDataUpdateCoordinator._update_vehicle of <custom_components.myskoda.coordinator.MySkodaDataUpdateCoordinator object at 0x7f9be0722570>>
Unexpected exception from <bound method MySkodaDataUpdateCoordinator._update_air_conditioning of <custom_components.myskoda.coordinator.MySkodaDataUpdateCoordinator object at 0x7f9be0722570>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 137, in _handle_timer_finish
    await task
  File "/config/custom_components/myskoda/coordinator.py", line 190, in _update_vehicle
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 267, in get_vehicle
    info = await self.get_info(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 220, in get_info
    return (await self.rest_api.get_info(vin, anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 107, in get_info
    data=await self._make_get_request(url),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 95, in _make_get_request
    return await self._make_request(url=url, method="GET")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 81, in _make_request
    headers=await self._headers(),
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 244, in _headers
    return {"authorization": f"Bearer {await self.authorization.get_access_token()}"}
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 293, in get_access_token
    await self.refresh_token()
  File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 262, in refresh_token
    if await self._perform_refresh_token():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 241, in _perform_refresh_token
    async with self.session.post(
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1355, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 492, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed

**Is this working in MySkoda app?***
App working without issues

**Latest working release**
1.4.0

**Debug logs**
If applicable, add debug logs. Debug logs help us locate and fix a problem quicker

**Installation:**
 - Home Assistant variant: Latest

**Comment by WebSpider** [comment]
Thanks for this report!

Can you explain a little bit what the impact of this error is on your install?

- Does HA still work
- Does the Myskoda integration still work
- Are all the sensors updating
- Anything else you're seeing

Thanks!

**Comment by arjanvroege** [comment]
Does HA still work
> Yes., but in the end it lost connection with the 'outside' world, was for instance not able to access HA through NabuCasa anymore. When logged on through the local IP every integration which uses the internet failed. After a restart of HA error was gone and haven't seen it after the restart.

Does the Myskoda integration still work
> Yes stayed working

Are all the sensors updating
> , sensors were updating

Anything else you're seeing
> Yesterday I was trying to activate the climate but did the same steps this evening and the error was not there. The other thing was that the car was charging at the moment the error occurred. But not sure if any of these two events can cause this error.

**Comment by arjanvroege** [comment]
This morning HA was again not accessible from the outside world. I've now disabled the integration to see if the integration is the root cause for the not accessible issue. Around the time that issues are starting I see the following entries in the log:

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:147
First occurred: October 22, 2024 at 23:34:12 (1 occurrences)
Last logged: October 22, 2024 at 23:34:12

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/mqtt.py", line 150, in connect
    await self._subscribe_to_topic(f"{user_id}/{vin}/operation-request/{topic}")
  File "/usr/local/lib/python3.12/site-packages/myskoda/mqtt.py", line 260, in _subscribe_to_topic
    raise ConcurrentSubscribeError
myskoda.mqtt.ConcurrentSubscribeError

After this error I started to see that HA and integrations cannot access the internet anymore because of DNS issues.

**Comment by WebSpider** [comment]
Thanks for the additional information!

I had already noticed the `ConcurrentSubscribeError` and created a seperate issue skodaconnect/myskoda#123 for it, so we can have a look.
Also, we've improved the robustness of the communication with the MySkoda API a bit in #123, which will be in the next release.

Could you maybe tell a little bit more about the way you run HA? Is it Windows/Linux? If Linux, do you run Core, Containerized or HAOS?

**Comment by arjanvroege** [comment]
Linux, I'm running HA on the Home Assistant Operating System. I've disabled the integration this morning and haven't seen the issue of the inaccessibility of HA. So it looks like this integration is causing the issue. Some versions back I had the same issue (also reported) which was resolved.. It looks like it's back. :-(

**Comment by WebSpider** [comment]
We have added some improvements on communications error handling in 1.6.2, can you try that one?

**Comment by WebSpider** [comment]
Version 1.6.4 has just been released that should fix this. Please update at your earliest convenience and let us know if you are still seeing this.
