### ISSUE TITLE
Image link does not look nice

### ISSUE THREAD

**Issue by fursov** [skodaconnect/homeassistant-myskoda#129]
Should the link for the car image be somewhat hidden, or be under some hyperlink/reference?
Currently this looks a bit ugly:

![image_url](https://github.com/user-attachments/assets/88b54d4a-a794-417e-81b0-9d3492bc7113)

**Comment by WebSpider** [comment]
OK, so im not the only one who is a bit annoyed by this.
Will look at hiding it!

**Comment by WebSpider** [comment]
I will attempt to convert it into an Image and see how that looks.

**Comment by arjanvroege** [comment]
One small addition on this one, It looks like its not an image entity. So at this moment hard to use it in dashboards. So I prefer to make it an image entity so that it can be used in the 'Picture' cards.

**Comment by WebSpider** [comment]
@arjanvroege i was on the same path. PR is submitted to make it an image entity.
Additionally this opens up the way to really easily include all the other renders.

**Comment by WebSpider** [comment]
Fixed in 1.6.3
