### ISSUE TITLE
No car identity in the entities names

### ISSUE THREAD

**Issue by fursov** [skodaconnect/homeassistant-myskoda#130]
**Is your feature request related to a problem? Please describe.**
The entities names are way too generic. For example, `switch.charging`, `climate.air_conditioning`. This might easily coincide with existing entities. So not clear what may happen if there are several cars in the garage.

**Describe the solution you'd like**
Like in the previous integration, car name can be added as prefix, e.g. `switch.my_superb_charging`, `climate.my_superb_air_conditioning`

**Comment by WebSpider** [comment]
Duplicate of #57 
If you remove your integration and re-add it, the entity names should make more sense
