### ISSUE TITLE
Add Portuguese Brazil

### ISSUE THREAD

**Issue by Lucasofchirstms** [skodaconnect/homeassistant-myskoda#133]
I know I'm repeating the same issue again, but I just want to tell that Portuguese and Portuguese Brazil are not the same, so I'll be thankful if you add it to the project

**Comment by WebSpider** [comment]
I will add this language somewhere today, and close this issue when done.

**Comment by WebSpider** [comment]
Crowdin has an awesome mobile interface these days. Pt_br added!
