### ISSUE TITLE
Renaming of entities to include the car type

### ISSUE THREAD

**Issue by AMajland** [skodaconnect/homeassistant-myskoda#136]
The old skoda connect integration added entities with the car as part of it.  So i have i,e
sensor.enyaq_odometer 
sensor.kodiaq_odometer
etc

With the MySkoda integration i instead have
sensor.milage
sensor.milage_2
etc
Their friendly name is very descriptive and include the car type (Kodiaq / Enayq ) 

Maybe use something unique as the frame number as as someone probably have two cars of the same model :-) 
Or maybe it would be even better to just move the many sensors to attributes on a main sensor ?

**Comment by WebSpider** [comment]
We changed this in 1.6, but you will have to re install the integration

**Comment by WebSpider** [comment]
We changed this in 1.6, but you will have to re install the integration

**Comment by AMajland** [comment]
Indeed it does :-)
![image](https://github.com/user-attachments/assets/08e5c282-485f-470f-a841-695d3038686f)
