### ISSUE TITLE
ValueError: 'GUEST_USER' is not a valid VehicleState

### ISSUE THREAD

**Issue by alphaspot** [skodaconnect/homeassistant-myskoda#138]
Logger: myskoda.rest_api
Kilde: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:376
Første forekomst: 00.08.28 (3 forekomster)
Senest logget: 00.48.30

Failed to deserialize data: {"vehicles":[{"vin":"REDACTED","name":"Enyaq","state":"GUEST_USER","devicePlatform":"WCAR","systemModelId":"5AZJJ2","title":"Škoda Enyaq","renders":[{"url":"https://iprenders.blob.core.windows.net/base5azv23200005/8E8EPUxFvBgM0CK-U_pbg0iQAkeurY6N8mR-9YvJAb12IOPUxtyog6_B-Mwqxg0_cFBhHk3YT16uJsbRolW8-CKGNEBJ-19201080dayvext_side1080.png","viewPoint":"exterior_side","type":"REAL","order":0},{"url":"https://ip-modcwp.azureedge.net/modcwp5azv23200005/8E8EPUxFvBgM0CK-U_pbg0iQAkeurY6N8mR-9YvJAb12IOPUxtyog6_B-Mwqxg0_cFBhHk3YT16uJsbRolW8-CKGNEBJ-1920658dayvext_side1080.png?v=638467251820000000","viewPoint":"garage_l","type":"REAL","order":1},{"url":"https://ip-modcwp.azureedge.net/modcwp5azv23200005/8E8EPUxFvBgM0CK-U_pbg0iQAkeurY6N8mR-9YvJAb12IOPUxtyog6_B-Mwqxg0_cFBhHk3YT16uJsbRolW8-CKGNEBJ-700390dayvext_front1080.png?v=638467251820000000","viewPoint":"main","type":"REAL","order":2}],"compositeRenders":[{"layers":[{"url":"https://iprenders.blob.core.windows.net/base5azv23200005/8E8EPUxFvBgM0CK-U_pbg0iQAkeurY6N8mR-9YvJAb12IOPUxtyog6_B-Mwqxg0_cFBhHk3YT16uJsbRolW8-CKGNEBJ-19201080dayvext_side1080.png","viewPoint":"exterior_side","type":"REAL","order":0}],"viewType":"UNMODIFIED_EXTERIOR_SIDE"}],"priority":0}]}
Traceback (most recent call last):
  File "<string>", line 14, in __mashumaro_from_dict_json__
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'GUEST_USER' is not a valid VehicleState

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 10, in __mashumaro_from_json__
  File "<string>", line 16, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "state" of type VehicleState in GarageEntry has invalid value 'GUEST_USER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 12, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "vehicles" of type Optional[list[GarageEntry]] in Garage has invalid value [{'vin': 'REDACTED', 'name': 'Enyaq', 'state': 'GUEST_USER', 'devicePlatform': 'WCAR', 'systemModelId': '5AZJJ2', 'title': 'Škoda Enyaq', 'renders': [{'url': 'https://iprenders.blob.core.windows.net/base5azv23200005/8E8EPUxFvBgM0CK-U_pbg0iQAkeurY6N8mR-9YvJAb12IOPUxtyog6_B-Mwqxg0_cFBhHk3YT16uJsbRolW8-CKGNEBJ-19201080dayvext_side1080.png', 'viewPoint': 'exterior_side', 'type': 'REAL', 'order': 0}, {'url': 'https://ip-modcwp.azureedge.net/modcwp5azv23200005/8E8EPUxFvBgM0CK-U_pbg0iQAkeurY6N8mR-9YvJAb12IOPUxtyog6_B-Mwqxg0_cFBhHk3YT16uJsbRolW8-CKGNEBJ-1920658dayvext_side1080.png?v=638467251820000000', 'viewPoint': 'garage_l', 'type': 'REAL', 'order': 1}, {'url': 'https://ip-modcwp.azureedge.net/modcwp5azv23200005/8E8EPUxFvBgM0CK-U_pbg0iQAkeurY6N8mR-9YvJAb12IOPUxtyog6_B-Mwqxg0_cFBhHk3YT16uJsbRolW8-CKGNEBJ-700390dayvext_front1080.png?v=638467251820000000', 'viewPoint': 'main', 'type': 'REAL', 'order': 2}], 'compositeRenders': [{'layers': [{'url': 'https://iprenders.blob.core.windows.net/base5azv23200005/8E8EPUxFvBgM0CK-U_pbg0iQAkeurY6N8mR-9YvJAb12IOPUxtyog6_B-Mwqxg0_cFBhHk3YT16uJsbRolW8-CKGNEBJ-19201080dayvext_side1080.png', 'viewPoint': 'exterior_side', 'type': 'REAL', 'order': 0}], 'viewType': 'UNMODIFIED_EXTERIOR_SIDE'}], 'priority': 0}]

**Comment by WebSpider** [comment]
Awesome, thanks!

We have not encountered a guest user yet, we will adjust the integration to suit this! 👍
