### ISSUE TITLE
Use capabilities to only create sensors that make sense for the vehicle

### ISSUE THREAD

**Issue by WebSpider** [skodaconnect/homeassistant-myskoda#15]
We should find a way to leverage capabilities in the future, in order to not enable sensors that don't make sense.

_Originally posted by @Prior99 in https://github.com/skodaconnect/homeassistant-myskoda/pull/8#discussion_r1763484391_

**Comment by Prior99** [comment]
This is implemented as of now. Can the issue be closed?
