### ISSUE TITLE
Remaining charging time doesn't have a unit

### ISSUE THREAD

**Issue by ChristianForstner** [skodaconnect/homeassistant-myskoda#150]
I created a pop-up to quickly see some stats about my car. 
You can see the state of charge (SoC), the car's range, and the remaining charging time. While the first two have units, the last one doesn't. 

![Screenshot_20241030-210401_edited.jpeg](https://github.com/user-attachments/assets/9de67bb2-3e1d-49f1-af49-1e661c84c90b)

Opening the sensor details also shows that it doesn't have a unit:

![Screenshot_20241030-210405_edited.jpeg](https://github.com/user-attachments/assets/b5e6c82a-59b0-41d3-b3eb-68e0be89ae3f)

I'm running version 1.6.4.

**Comment by WebSpider** [comment]
There is a unit, it's minutes by default. Have a look at the left, under "Verlauf". The unit is displayed there as `min`

**Comment by ChristianForstner** [comment]
Ok, but shouldn't the unit also be displayed for the current value like it's done e.g. for the car's range?
![Screenshot_20241031-092648_edited~2.jpeg](https://github.com/user-attachments/assets/7adbd87b-0d10-4a4e-a1cb-07ba3e4547e4)
![Screenshot_20241031-093117.png](https://github.com/user-attachments/assets/814d4f39-4bc2-4e8c-9e3f-22f7d66306a0)

Or is this maybe a bug (feature?) of Home Assistant itself?

**Comment by WebSpider** [comment]
I see what you mean. 
In the definition of the two sensors there is one minor difference, that should only influence statistics. Ill tinker around a bit and see if syncing that makes any difference.

**Comment by WebSpider** [comment]
Nope, that does not make any difference. I'll dig deeper.

**Comment by WebSpider** [comment]
It turns out there are quite some bugs in the frontend when it comes to the `DURATION` type sensor (which this is as well).

**Comment by WebSpider** [comment]
As a workaround, you can add a template sensor to wrap around the sensor the integration gives you, or use an alternate frontend card. As soon as frontend solves this, we'll update this issue

**Comment by ChristianForstner** [comment]
Thanks for the deep dive into the underlying reason. I think, I will just keep it as it is right now and wait until frontend solves this, since remembering the unit being `min` isn't that much of an effort.
