### ISSUE TITLE
Support configurable poll frequency

### ISSUE THREAD

**Issue by dvx76** [skodaconnect/homeassistant-myskoda#151]
We currently have a hardcoded poll frequency of 30m. This is based on the assumption that any notable event will have an associated MQTT event which will result in entities being updated. In reality we're seeing that's not always the case. One example is that some Enyaq owners see soc events every 1% charger while other only every 10% charger.

Discord convo: https://discord.com/channels/877164727636230184/877167631935897621/1301289245951918152

The request here is to:
- Make the 'normal' (i.e. unrelated to MQTT) poll frequency configurable, keeping the default at 30m
- Probably set a low value limit (I personally used to run 30s on the old integration and never had issues but I know there are many other users who will hit 429's with a 30s poll interval)
- Document this and make it abundantly clear you can shoot yourself in the foot

**Comment by WebSpider** [comment]
I've given this some thought, and while I think you should be able to configure this yourself, I prefer that we make an educated guess ourselves to see if MQTT is working by:

1. Recording the date/time of last received MQTT message
2. Comparing this with captured date/time at polls

If we then conclude we are missing MQTT messages, raise the polling interval, and if we get MQTT messages again, lower it.

**Comment by WebSpider** [comment]
As discussed on Discord as well: My suggestion is making things more complex.

Let's stick with a configurable poll frequency, combined with:

```yaml
action: homeassistant.update_entity
data:
  entity_id:
    - sensor.mycar_mysensor
```
