### ISSUE TITLE
Skoda Kodiaq II (2024) - no binary sensors or switches available

### ISSUE THREAD

**Issue by Tomanic-glitch** [skodaconnect/homeassistant-myskoda#164]
Thank you very much for this integration. I have added Skoda Kodiaq II (2024) and only see limited amount of sensors in the integration but no binary sensors or switches. Is this what should be expected with my diesel car?

![available_entities](https://github.com/user-attachments/assets/d6b1f69f-0bab-4ea5-8560-c91d5827fa17)

**Comment by WebSpider** [comment]
You are in fact getting abunch of `binary_sensor`s, since Bonnet, Doors, Lock, Lights, Sunroof, Trunk, Windows are all binary sensors.

As for the amount of switches: Most of them are related to charging and battery, but if you have window-heating, I would have expected a switch for that.

**Comment by dvx76** [comment]
Yeah this looks more or less like what I would expect. I don't think we have raw data from a Kodiaq yet. Take a look at https://github.com/skodaconnect/myskoda?tab=readme-ov-file#contribute-your-fixtures . If that is something you are comfortable doing it would be helpful for us so we can see exactly what data the API is returning for your specific car. Also if there are things you can see or do in the official MySkoda app which aren't available in the integration that is always good for us to know about.

**Comment by Tomanic-glitch** [comment]
I have only very little experience with Python but in the attached TXT is the output I get when running # Export all endpoints for a specific vehicle.

I'm also adding all the sensors and switches I get with the Skoda Connect integration if it's of any use. And if I can help any further don't hesitate to ask.

[output.txt](https://github.com/user-attachments/files/17619371/output.txt)
![Skoda_Connect_1](https://github.com/user-attachments/assets/df45fe88-b93c-48e4-b052-773bc2b06692)
![Skoda_Connect_2](https://github.com/user-attachments/assets/1acffdde-f690-4ed6-8977-89f32b95de37)
![Skoda_Connect_3](https://github.com/user-attachments/assets/9e049d7f-fba1-47c5-b9ff-9d9f3ded19b2)

**Comment by WebSpider** [comment]
Going though the entities here:
## Controls
- Door/trunk/etc lock: We currently don't have a way to detect if your car supports remote locking. Once we find this out, we can add it as a lock you can operate. Currently we show you the status.
- Force data refresh: We support that using the `homeassistant.update_entity` action.
- Parking Heater: We have not found support for this in MySkoda API's yet
- Parking Heater Ventilation: We have not found support for this in MySkoda API's yet
- Flash and Honk: We've just discovered it, and are looking at adding this.

## Sensors
- AdBlue level: We have not found support for this in MySkoda API's yet
- Car Info: We don't expose that as an entity, it is in the Device Serial nr
- Combustion range: We've just discovered it, and are looking at adding this.
- Individual door lock statuses: We have not found support for this in MySkoda API's yet
- All door lock statuses: Present
- Fuel level: We've just discovered it, and are looking at adding this.
- Hood status: Present
- Last connected: Present
- Trip and longterm statistics: We've just discovered it, and are looking at adding this.
- Model image: Present
- Odometer: Present
- Oil inspection: We have not found support for this in MySkoda API's yet
- Outside temperature: We have not found support for this in MySkoda API's yet
- Parking heater status: We have not found support for this in MySkoda API's yet
- Parking light statys: We have not found support for this in MySkoda API's yet
- Parking time: We have not found support for this in MySkoda API's yet
- Refuel statistics: We have not found support for this in MySkoda API's yet
- Request counters: No longer exposed in MySkoda API
- Service inspection: Present in 1.7.2+
- Sunroof status: Present

**Comment by Tomanic-glitch** [comment]
Thank you very much for the info, meanwhile if it could help I'm adding the full zipped yaml with output from # Export all endpoints for a specific vehicle

[my_favorite_car.zip](https://github.com/user-attachments/files/17647266/my_favorite_car.zip)

**Comment by dvx76** [comment]
@WebSpider do we want to split this into separate issues? Seems unlikely everything will be added at once.

**Comment by WebSpider** [comment]
Yes, i have been thinking about this as well. Lets split it out, so the tasks are manageable.
