### ISSUE TITLE
Failed to deserialize data: {"vehicles":[{"vin":"xxxxxxxxxxxx","name":"Skoda Superb L&K","state":"ACTIVATED",

### ISSUE THREAD

**Issue by msandvold** [skodaconnect/homeassistant-myskoda#190]
Wanted to test this integration.
Error loging inn - An unexpected error occurred. Please check the HomeAssistant logfiles.

My car is a Skoda Superb MK3 L&K 2017/2018

Log:

Logger: myskoda.rest_api
Kilde: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:376
Førs oppstått: 22:45:57 (1 hendelser)
Sist logget: 22:45:57

Failed to deserialize data: {"vehicles":[{"vin":"xxxxxxxxxxxxx","name":"Skoda Superb L&K","state":"ACTIVATED","devicePlatform":"MBB","systemModelId":"3V55UX","title":"Škoda Superb Combi","renders":[{"url":"https://iprenders.blob.core.windows.net/base3v5b20180115/F6F6I-.7-v2EShuCLalrA6qGQ0-Xw82WTDMLQB56_z-ENyACWiZvte6V7pGJn0r.hQ_l3-Ov52r8mdiWlxXDBF0hPtb-RATWGKBF-19201080dayvext_side1080.png","viewPoint":"exterior_side","type":"REAL","order":0},{"url":"https://ip-modcwp.azureedge.net/modcwp3v5b20180115/F6F6I-.7-v2EShuCLalrA6qGQ0-Xw82WTDMLQB56_z-ENyACWiZvte6V7pGJn0r.hQ_l3-Ov52r8mdiWlxXDBF0hPtb-RATWGKBF-700390dayvext_front1080.png?v=637859744820000000","viewPoint":"main","type":"REAL","order":1}],"compositeRenders":[{"layers":[{"url":"https://iprenders.blob.core.windows.net/base3v5b20180115/F6F6I-.7-v2EShuCLalrA6qGQ0-Xw82WTDMLQB56_z-ENyACWiZvte6V7pGJn0r.hQ_l3-Ov52r8mdiWlxXDBF0hPtb-RATWGKBF-19201080dayvext_side1080.png","viewPoint":"exterior_side","type":"REAL","order":0}],"viewType":"UNMODIFIED_EXTERIOR_SIDE"}],"priority":0}],"errors":[{"type":"MISSING_RENDER","description":"Getting render of view point {garage_l} for vehicle VIN {TMBLE9NP2J7516216} failed with message {404 Not Found from GET http://render-service/api/v1/renders/TMBLE9NP2J7516216}"}]}
Traceback (most recent call last):
  File "<string>", line 11, in __mashumaro_from_dict_json__
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'MISSING_RENDER' is not a valid GarageErrorType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in __mashumaro_from_json__
  File "<string>", line 13, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "type" of type GarageErrorType in GarageError has invalid value 'MISSING_RENDER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 19, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "errors" of type Optional[list[GarageError]] in Garage has invalid value [{'type': 'MISSING_RENDER', 'description': 'Getting render of view point {garage_l} for vehicle VIN {TMBLE9NP2J7516216} failed with message {404 Not Found from GET http://render-service/api/v1/renders/TMBLE9NP2J7516216}'}]

**Comment by WebSpider** [comment]
Thanks for your report!

This is the first time we see this type of car in this integration. We'll add support for the missing data in the next release!

**Comment by jamiegt10** [comment]
Good Morning, i also get this error with my account, i have my Superb iV and my wife's Rapid linked to it: 

Failed to deserialize data: {"vehicles":[{"vin":"xxx","name":"Superb iV","licensePlate":"xxx","state":"ACTIVATED","devicePlatform":"MBB_ODP","systemModelId":"3V5RXC","title":"Škoda Superb Combi","renders":[{"url":"https://skodavinimagecache.blob.core.windows.net/cache3v5s21101106/8X8XFKOA-mot-Oc4fe9-L084EeZw9n5jysHXc-gCjO1uYE5PnSeLApXsad-i2amYSAvVPK9OybDeprtLh8H0-YolcKkRNDePVTJpHgAB-19201080dayvext_side1080.png","viewPoint":"exterior_side","type":"REAL","order":0},{"url":"https://ip-modcwp.azureedge.net/modcwp3v5s21101106/8X8XFKOA-mot-Oc4fe9-L084EeZw9n5jysHXc-gCjO1uYE5PnSeLApXsad-i2amYSAvVPK9OybDeprtLh8H0-YolcKkRNDePVTJpHgAB-1920658dayvext_side1080.png?v=638412904620000000","viewPoint":"garage_l","type":"REAL","order":1},{"url":"https://ip-modcwp.azureedge.net/modcwp3v5s21101106/8X8XGKNA-lot-Oa4fe9-J084EfZw9m5jysHXc-gCjO1wYE4PnSeLApXsad-j2amYSAvVPK9OybDeprtLh8F0-YolcKjRNDePWTJpHgAC-700390dayvext_front1080.png?v=637859733960000000","viewPoint":"main","type":"REAL","order":2}],"compositeRenders":[{"layers":[{"url":"https://skodavinimagecache.blob.core.windows.net/cache3v5s21101106/8X8XFKOA-mot-Oc4fe9-L084EeZw9n5jysHXc-gCjO1uYE5PnSeLApXsad-i2amYSAvVPK9OybDeprtLh8H0-YolcKkRNDePVTJpHgAB-19201080dayvext_side1080.png","viewPoint":"exterior_side","type":"REAL","order":0}],"viewType":"UNMODIFIED_EXTERIOR_SIDE"}],"priority":0},{"vin":"xxx","name":"RAPID","state":"ACTIVATED","devicePlatform":"MBB","systemModelId":"NH13N5","title":"Škoda Rapid Spaceback","renders":[{"url":"https://iprenders.blob.core.windows.net/transnh1b20180219/8X8XM--59naqmg3fjs-sR_YfKliLpHCnbFXP-pZ0vlj35c2uYy.-0NPKgeJYt9bUlv13hrx-0tvdzTnfgrPiXEMkR-19201080dayvext_side1080.png?v=638665620664797076","viewPoint":"exterior_side","type":"REAL","order":0},{"url":"https://ip-modcwp.azureedge.net/modcwpnh1b20180219/8X8XM--59naqmg3fjs-sR_YfKliLpHCnbFXP-pZ0vlj35c2uYy.-0NPKgeJYt9bUlv13hrx-0tvdzTnfgrPiXEMkR-700390dayvext_front1080.png?v=637862975620000000","viewPoint":"main","type":"REAL","order":1}],"compositeRenders":[{"layers":[{"url":"https://iprenders.blob.core.windows.net/transnh1b20180219/8X8XM--59naqmg3fjs-sR_YfKliLpHCnbFXP-pZ0vlj35c2uYy.-0NPKgeJYt9bUlv13hrx-0tvdzTnfgrPiXEMkR-19201080dayvext_side1080.png?v=638665620664797076","viewPoint":"exterior_side","type":"REAL","order":0}],"viewType":"UNMODIFIED_EXTERIOR_SIDE"}],"priority":1}],"errors":[{"type":"MISSING_RENDER","description":"Getting render of view point {garage_l} for vehicle VIN {xxx} failed with message {404 Not Found from GET http://render-service/api/v1/renders/xxx}"}]}

**Comment by linkweaver** [comment]
Hi,

I have the same problem too

My vehicle is a Skoda Kodak 2017 and API return : 


Failed to deserialize data: {"vehicles":[{"vin":"XXX","name":"KODIAQ","state":"ACTIVATED","devicePlatform":"MBB","systemModelId":"NS745D","title":"Škoda Kodiaq","renders":[{"url":"https://iprenders.blob.core.windows.net/transns7b20180105/9P9PD-36941.-ltfFj_3B7Uc1Nvash-WjvCFn3oq_kxzg6-tyaBrJYWvE8gR_jlPeU3HiN-r0kQo9hHbsWcNeJS5Dm1Vuw3L-AC-19201080dayvext_side1080.png?v=638665218931095822","viewPoint":"exterior_side","type":"REAL","order":0},{"url":"https://ip-modcwp.azureedge.net/modcwpns7b20180105/9P9PD-36941.-ltfFj_3B7Uc1Nvash-WjvCFn3oq_kxzg6-tyaBrJYWvE8gR_jlPeU3HiN-r0kQo9hHbsWcNeJS5Dm1Vuw3L-AC-700390dayvext_front1080.png?v=637887166060000000","viewPoint":"main","type":"REAL","order":1}],"compositeRenders":[{"layers":[{"url":"https://iprenders.blob.core.windows.net/transns7b20180105/9P9PD-36941.-ltfFj_3B7Uc1Nvash-WjvCFn3oq_kxzg6-tyaBrJYWvE8gR_jlPeU3HiN-r0kQo9hHbsWcNeJS5Dm1Vuw3L-AC-19201080dayvext_side1080.png?v=638665218931095822","viewPoint":"exterior_side","type":"REAL","order":0}],"viewType":"UNMODIFIED_EXTERIOR_SIDE"}],"priority":0}],"errors":[{"type":"MISSING_RENDER","description":"Getting render of view point {garage_l} for vehicle VIN {XXX} failed with message {404 Not Found from GET http://render-service/api/v1/renders/XXX}"}]}

Thank you !

Regards,

Mathieu

**Comment by matnoublanche** [comment]
Hi,

I have the same problem too

My vehicle is a Skoda Kodak 2017 and API return :

Failed to deserialize data: {"vehicles":[{"vin":"XXX","name":"KODIAQ","state":"ACTIVATED","devicePlatform":"MBB","systemModelId":"NS745D","title":"Škoda Kodiaq","renders":[{"url":"https://iprenders.blob.core.windows.net/transns7b20180105/9P9PD-36941.-ltfFj_3B7Uc1Nvash-WjvCFn3oq_kxzg6-tyaBrJYWvE8gR_jlPeU3HiN-r0kQo9hHbsWcNeJS5Dm1Vuw3L-AC-19201080dayvext_side1080.png?v=638665218931095822","viewPoint":"exterior_side","type":"REAL","order":0},{"url":"https://ip-modcwp.azureedge.net/modcwpns7b20180105/9P9PD-36941.-ltfFj_3B7Uc1Nvash-WjvCFn3oq_kxzg6-tyaBrJYWvE8gR_jlPeU3HiN-r0kQo9hHbsWcNeJS5Dm1Vuw3L-AC-700390dayvext_front1080.png?v=637887166060000000","viewPoint":"main","type":"REAL","order":1}],"compositeRenders":[{"layers":[{"url":"https://iprenders.blob.core.windows.net/transns7b20180105/9P9PD-36941.-ltfFj_3B7Uc1Nvash-WjvCFn3oq_kxzg6-tyaBrJYWvE8gR_jlPeU3HiN-r0kQo9hHbsWcNeJS5Dm1Vuw3L-AC-19201080dayvext_side1080.png?v=638665218931095822","viewPoint":"exterior_side","type":"REAL","order":0}],"viewType":"UNMODIFIED_EXTERIOR_SIDE"}],"priority":0}],"errors":[{"type":"MISSING_RENDER","description":"Getting render of view point {garage_l} for vehicle VIN {XXX} failed with message {404 Not Found from GET http://render-service/api/v1/renders/XXX}"}]}

Thank you !

Regards,

Mathieu

**Comment by RamsesczHA** [comment]
Hi, 

same problem for me.

My car is Skoda Octavia Combi 3 L&K 2018

2024-11-07 08:37:00.639 ERROR (MainThread) [myskoda.rest_api] Failed to deserialize data: {"vehicles":[{"vin":"XXX","name":"Octavia","licensePlate":"4SL9132","state":"ACTIVATED","devicePlatform":"MBB","systemModelId":"5E558C","title":"Škoda Octavia Combi","renders":[{"url":"https://iprenders.blob.core.windows.net/trans5e5b29180112/8E8EF--nPUjVRuNX-rmhj5FWOgyIvbp-JoGFC-NEJ5hTWr1sZypKdbOC9j08-31Fr9YBTws5oiH8MKOfznAJu-PKj4mA9UckyL0e5g2o.ZsuG-B-19201080dayvext_side1080.png?v=638665182663690983","viewPoint":"exterior_side","type":"REAL","order":0},{"url":"https://ip-modcwp.azureedge.net/modcwp5e5b29180112/8E8EF--nPUjVRuNX-rmhj5FWOgyIvbp-JoGFC-NEJ5hTWr1sZypKdbOC9j08-31Fr9YBTws5oiH8MKOfznAJu-PKj4mA9UckyL0e5g2o.ZsuG-B-700390dayvext_front1080.png?v=638519581720000000","viewPoint":"main","type":"REAL","order":1}],"compositeRenders":[{"layers":[{"url":"https://iprenders.blob.core.windows.net/trans5e5b29180112/8E8EF--nPUjVRuNX-rmhj5FWOgyIvbp-JoGFC-NEJ5hTWr1sZypKdbOC9j08-31Fr9YBTws5oiH8MKOfznAJu-PKj4mA9UckyL0e5g2o.ZsuG-B-19201080dayvext_side1080.png?v=638665182663690983","viewPoint":"exterior_side","type":"REAL","order":0}],"viewType":"UNMODIFIED_EXTERIOR_SIDE"}],"priority":0}],"errors":[{"type":"MISSING_RENDER","description":"Getting render of view point {garage_l} for vehicle VIN {XXX} failed with message {404 Not Found from GET http://render-service/api/v1/renders/XXX}"}]}
