### ISSUE TITLE
Error occurred while sending password. Password may be incorrect.

### ISSUE THREAD

**Issue by pathia** [skodaconnect/homeassistant-myskoda#194]
I get an error while trying to add the integration "Error occurred while sending password. Password may be incorrect."

**Is this working in MySkoda app?***
Yes

**Latest working release**
dunno, first time installation

**Debug logs**
aiohttp.client_exceptions.InvalidUrlClientError: 
myskoda.auth.authorization.AuthorizationFailedError
I'm unsure what details I can share here visible for the public.

**Installation:**
Hass OS 
Package    Version
---------- -------
awake      1.0
packaging  24.0
pathspec   0.12.1
pip        24.0
pulsemixer 1.5.1
pyparsing  3.1.2
PyYAML     6.0.2
setuptools 70.3.0
yamllint   1.35.1

**Additional context**
I'm wild guessing it has to do with the special characters in my password along with the encoding you use. It contains the following chars: asterisk, dollar sign and the hashtag sign

**Comment by pathia** [comment]
That was indeed the problem. I'm logged in now. Thanks!
I see a lot less sensors. And no way to remote lock the car? Or is this still a work in progress perhaps?
Is a 'bonnet' the front cover which covers the engine?

**Comment by WebSpider** [comment]
- Less sensors: Correct, see https://github.com/skodaconnect/homeassistant-myskoda/issues/164#issuecomment-2459632073
- Remote lock: Currently being developed, see https://github.com/skodaconnect/myskoda/pull/167
- Bonnet: Yes, it is also known as "hood"

**Comment by WebSpider** [comment]
I'm going ahead and close the issue, I think this has been sufficiently answered. Feel free to reopen if there is anything left :+1:

**Comment by pathia** [comment]
Sure, you helped me big time. Thanks!! Go ahead and close 👍 
And since English is not my mothers language I only know the name hood and not bonnet. I've renamed it in my HA :-)
Also a huge thanks for your hard work for this new integration with the new api
