### ISSUE TITLE
Skoda Kamiq not yet supported

### ISSUE THREAD

**Issue by MarcoGos** [skodaconnect/homeassistant-myskoda#202]
First of all thank you for willing to maintain/create a new integration for Skoda.

When I start the integration the following error occurs:

Failed to deserialize data: {"vin":"xxxxxxxxxxx","name":"Kamiq","workshopModeEnabled":false,"licensePlate":"xxxxxxx","state":"ACTIVATED","devicePlatform":"MBB_ODP","specification":{"title":"Škoda Kamiq","manufacturingDate":"2021-02-10","model":"Kamiq","modelYear":"2021","body":"Crossover","systemCode":"UNKNOWN","systemModelId":"NW44KD","engine":{"type":"TSI","powerInKW":110,"capacityInLiters":1.5},"gearbox":{"type":"A7F"}},"servicePartner":{"servicePartnerId":"NLDC00156"},"renders":[{"url":"https://skodavinimagecache.blob.core.windows.net/cachenw4s21201021/0F0F.t8RiJgm-IcSa0qTEufOlvBkVdoQ-ZoU37WQvu9espcI0TxjG-epBt81ymG4_liJ-Z0Owlb.iL4rCSFKnQ8fx5-boDIdhkCTqWgnKRiZt-19201080dayvext_side1080.png","viewPoint":"exterior_side","type":"REAL","order":0},{"url":"https://ip-modcwp.azureedge.net/modcwpnw4s21201021/0F0F.t8RiJgm-IcSa0qTEufOlvBkVdoQ-ZoU37WQvu9espcI0TxjG-epBt81ymG4_liJ-Z0Owlb.iL4rCSFKnQ8fx5-boDIdhkCTqWgnKRiZt-1920658dayvext_side1080.png?v=638625258530000000","viewPoint":"garage_l","type":"REAL","order":1},{"url":"https://ip-modcwp.azureedge.net/modcwpnw4s21201021/0F0F.t8RiJgm-IcSa0qTEufOlvBkVdoQ-ZoU37WQvu9espcI0TxjG-epBt81ymG4_liJ-Z0Owlb.iL4rCSFKnQ8fx5-boDIdhkCTqWgnKRiZt-700390dayvext_front1080.png?v=637859752970000000","viewPoint":"main","type":"REAL","order":2}],"compositeRenders":[{"layers":[{"url":"https://skodavinimagecache.blob.core.windows.net/cachenw4s21201021/0F0F.t8RiJgm-IcSa0qTEufOlvBkVdoQ-ZoU37WQvu9espcI0TxjG-epBt81ymG4_liJ-Z0Owlb.iL4rCSFKnQ8fx5-boDIdhkCTqWgnKRiZt-19201080dayvext_side1080.png","viewPoint":"exterior_side","type":"REAL","order":0}],"viewType":"UNMODIFIED_EXTERIOR_SIDE"},{"layers":[{"url":"https://skodavinimagecache.blob.core.windows.net/cachenw4s21201021/0F0F.t8RiJgm-IcSa0qTEufOlvBkVdoQ-ZoU37WQvu9espcI0TxjG-epBt81ymG4_liJ-Z0Owlb.iL4rCSFKnQ8fx5-boDIdhkCTqWgnKRiZt-19201080dayvext_side1080.png","viewPoint":"exterior_side","type":"REAL","order":0}],"modifications":{"adjustSpaceInPx":{"top":-338,"bottom":-201,"left":-187,"right":-206},"densityIndependentHeight":270,"flipHorizontal":false,"anchorTo":"LEFT"},"viewType":"HOME"}],"capabilities":{"capabilities":[{"id":"ACCESS","statuses":[]},{"id":"DEALER_APPOINTMENT","statuses":[]},{"id":"GEO_FENCE","statuses":[]},{"id":"HONK_AND_FLASH","statuses":[]},{"id":"MEASUREMENTS","statuses":[]},{"id":"NEWS","statuses":["LICENSE_MISSING"]},{"id":"PARKING_POSITION","statuses":[]},{"id":"ROADSIDE_ASSISTANT","statuses":[]},{"id":"SPEED_ALERT","statuses":[]},{"id":"STATE","statuses":[]},{"id":"TRIP_STATISTICS","statuses":[]},{"id":"VEHICLE_HEALTH_INSPECTION","statuses":[]},{"id":"WARNING_LIGHTS","statuses":[]},{"id":"VEHICLE_WAKE_UP","statuses":[]},{"id":"PAY_TO_FUEL","statuses":[]},{"id":"CUBIC","statuses":[]},{"id":"SUBSCRIPTIONS","statuses":[]},{"id":"DESTINATIONS","statuses":["LICENSE_MISSING","LICENSE_EXPIRED"]},{"id":"ICE_VEHICLE_RTS","statuses":[]},{"id":"OUTSIDE_TEMPERATURE","statuses":[]},{"id":"DIGICERT","statuses":[]},{"id":"VEHICLE_HEALTH_WARNINGS","statuses":[]},{"id":"PAY_TO_PARK","statuses":[]},{"id":"FUEL_STATUS","statuses":[]},{"id":"SERVICE_PARTNER","statuses":[]},{"id":"ROUTE_IMPORT","statuses":[]},{"id":"MISUSE_PROTECTION","statuses":[]}]}}

Traceback (most recent call last):
  File "<string>", line 9, in __mashumaro_from_dict_json__
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'Crossover' is not a valid BodyType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in __mashumaro_from_json__
  File "<string>", line 11, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "body" of type BodyType in Specification has invalid value 'Crossover'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 19, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "specification" of type Specification in Info has invalid value {'title': 'Škoda Kamiq', 'manufacturingDate': '2021-02-10', 'model': 'Kamiq', 'modelYear': '2021', 'body': 'Crossover', 'systemCode': 'UNKNOWN', 'systemModelId': 'NW44KD', 'engine': {'type': 'TSI', 'powerInKW': 110, 'capacityInLiters': 1.5}, 'gearbox': {'type': 'A7F'}}

**Comment by WebSpider** [comment]
Thanks for your report!

We have not encountered this car before, so a few values are missing. We will add them and fix this error in the next release.

**Comment by WebSpider** [comment]
This is fixed in v1.8.0 of the integration.
