### ISSUE TITLE
Integration not working for Skoda Octavia (2017) yet

### ISSUE THREAD

**Issue by pmunck86** [skodaconnect/homeassistant-myskoda#203]
Hi, thanks for working on this integration! When trying to login, I get this error message:

Logger: myskoda.rest_api
Quelle: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:376
Erstmals aufgetreten: 20:21:28 (2 Vorkommnisse)
Zuletzt protokolliert: 20:24:10

Failed to deserialize data: {"vehicles":[{"vin":"xxx","name":"Octavia","state":"ACTIVATED","devicePlatform":"MBB","systemModelId":"5E53MD","title":"Škoda Octavia Combi","renders":[{"url":"https://iprenders.blob.core.windows.net/trans5e5b29180112/F6F6H--n8PUkVRxNb-rmhk5WeyPIvap-JnGFC-EJ5hTWqM1sZwoKdbOC9.jz8-31Er9cBTws5ohH8lMKOfzIu-Pi4mA9UckIyLze5h2o.ZtuG-B-19201080dayvext_side1080.png?v=638666038814146147","viewPoint":"exterior_side","type":"REAL","order":0},{"url":"https://ip-modcwp.azureedge.net/modcwp5e5b29180112/F6F6H--n8PUkVRxNb-rmhk5WeyPIvap-JnGFC-EJ5hTWqM1sZwoKdbOC9.jz8-31Er9cBTws5ohH8lMKOfzIu-Pi4mA9UckIyLze5h2o.ZtuG-B-700390dayvext_front1080.png?v=637859741150000000","viewPoint":"main","type":"REAL","order":1}],"compositeRenders":[{"layers":[{"url":"https://iprenders.blob.core.windows.net/trans5e5b29180112/F6F6H--n8PUkVRxNb-rmhk5WeyPIvap-JnGFC-EJ5hTWqM1sZwoKdbOC9.jz8-31Er9cBTws5ohH8lMKOfzIu-Pi4mA9UckIyLze5h2o.ZtuG-B-19201080dayvext_side1080.png?v=638666038814146147","viewPoint":"exterior_side","type":"REAL","order":0}],"viewType":"UNMODIFIED_EXTERIOR_SIDE"}],"priority":0}],"errors":[{"type":"MISSING_RENDER","description":"Getting render of view point {garage_l} for vehicle VIN {xxx} failed with message {404 Not Found from GET http://render-service/api/v1/renders/xxx}"}]}
Traceback (most recent call last):
  File "<string>", line 11, in __mashumaro_from_dict_json__
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'MISSING_RENDER' is not a valid GarageErrorType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in __mashumaro_from_json__
  File "<string>", line 13, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "type" of type GarageErrorType in GarageError has invalid value 'MISSING_RENDER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 374, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 19, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "errors" of type Optional[list[GarageError]] in Garage has invalid value [{'type': 'MISSING_RENDER', 'description': 'Getting render of view point {garage_l} for vehicle VIN {xxx} failed with message {404 Not Found from GET http://render-service/api/v1/renders/xxx}'}]

**Comment by dvx76** [comment]
Dup of #190, fixed in https://github.com/skodaconnect/myskoda/pull/164

Will come in next release.
