### ISSUE TITLE
Next Inspection need convert to days

### ISSUE THREAD

**Issue by chodorenko** [skodaconnect/homeassistant-myskoda#205]
Next Inspection now show as time, need show in days
<img width="363" alt="screen" src="https://github.com/user-attachments/assets/95c3fe2a-1231-45b3-a5f4-4f9c025ddedf">

**Comment by dvx76** [comment]
This is going to be an HA frontend thing in the device overview showing the value converted to HH:MM:SS. The unit _is_ days and if you use the entity in a card it should show it as days.

![image](https://github.com/user-attachments/assets/a5645a43-7015-4fe1-ac98-0cdf3af401e2)

![image](https://github.com/user-attachments/assets/e76c72dc-dfe0-415d-be60-8dbfec9ed1e6)

**Comment by chodorenko** [comment]
@dvx76 
at the same on manual card 
<img width="902" alt="image" src="https://github.com/user-attachments/assets/247fb233-2098-4660-8aee-472651caaba6">

On integration Skoda Connect all show correctly on HA frontend thing in the device overview and on different cards

**Comment by dvx76** [comment]
Depends on which card you use. See for e.g. difference between entity and entities card (standard HA cards). This is an HA thing, not something we can fix in the integration. See for e.g. discussion here: https://community.home-assistant.io/t/option-to-convert-duration-sensors-in-different-cards/515258


![image](https://github.com/user-attachments/assets/678fca9f-4bc4-42e7-9bf5-080f5a694a59)

**Comment by chodorenko** [comment]
@dvx76 
Certainly, I understand that from a programming style perspective, this approach makes sense. However, for a regular user, it might look quite confusing.

In my opinion, we have two options: either raise this issue with the Home Assistant development team or implement a conversion in our own code to display the value directly in days (as I believe this would be the faster solution).

**Comment by dvx76** [comment]
There is nothing to convert. We _already_ provide (to HA) the value in days. See https://github.com/skodaconnect/homeassistant-myskoda/blob/92d4b598888b305b4f3ca62e004d24e1113b59d8/custom_components/myskoda/sensor.py#L224

HA knows it's a duration and knows the unit is in days. How it then decides to present that information in certain views and cards is unrelated to this integration.

Feel free to open an issue in HA core. Likely this has already been reported though so would be good to search first. There certainly are multiple posts on the HA forums about it. https://github.com/home-assistant/core/issues

**Comment by msandvold** [comment]
sensor.xxxx_service_inspection_days from [Skodaconnect](https://github.com/skodaconnect/homeassistant-skodaconnect)
Shows "days", does not depend on which card you use.

![inspection_in](https://github.com/user-attachments/assets/b208baf2-81c3-4785-921a-e6334383ded3)

**Comment by dvx76** [comment]
Then the old integration must not be setting the device_class, state_class and/or unit correctly so HA doesn't actually understand what the sensor represents and can only render it as the actual value + the unit.
