### ISSUE TITLE
BinarySensor Vehicle_moving

### ISSUE THREAD

**Issue by mutzl** [skodaconnect/homeassistant-myskoda#206]
The old integration had a binary sensor `vehicle_moving`.

Any chance, that we get this information also from the new api?

**Comment by dvx76** [comment]
The device tracker should show `vehicle_in_motion` when it's moving (and the matching HA location name when it's not moving and the position is known). Can you work with that?

![image](https://github.com/user-attachments/assets/8028be19-3f03-47c6-bed3-bee7605ff923)
