### ISSUE TITLE
Additional range parameters.

### ISSUE THREAD

**Issue by BlaShDD** [skodaconnect/homeassistant-myskoda#211]
The integration now works for me. Thanks for that. I still have a few suggestions / wishes.

- 'next inspection' is displayed in hours instead of days.
- Internal combustion engines also have an oil change interval. Can this also be displayed?
- Both points above as time and distance.
- Add fuel range
- Add AdBlue range for diesel engines
- Software-Version shows unknown on Octavia NX

**Comment by WebSpider** [comment]
> * 'next inspection' is displayed in hours instead of days. 

This unfortunately is a bug in homeassistant-frontend for all `DURATION` type sensors. Once they solve it, this becomes days as well. If you are annoyed by this, you can solve it in the mean time by using a `template` sensor.

> * Internal combustion engines also have an oil change interval. Can this also be displayed?
> * Both points above as time and distance.
> * Add fuel range
> * Add AdBlue range for diesel engines

We've only just gotten reports from users that have cars that are not electric, so we're adjusting for this. Expect improvements soon :+1: 

> * Software-Version shows unknown on Octavia NX

That's a bug. I will open a separate issue for this

**Comment by WebSpider** [comment]
> Additional thoughts: I think the software version is only interesting for MEB vehicles. It is not relevant for MQB and I could simply hide it.

This may be a valid point. I'll look at the fixtures we have to see if there is a consistency to be found, and possibly only create that sensor when it makes sense.

**Comment by dvx76** [comment]
Do we keep this issue open? If so, which specific features will be tracked here? (I would prefer separate issues for each feature to be developed)

**Comment by WebSpider** [comment]
> Do we keep this issue open? If so, which specific features will be tracked here? (I would prefer separate issues for each feature to be developed)

I agree. Lets use #164 as a basis to create new enhancement issues from.
