### ISSUE TITLE
Too many requests occurred during getting warning lights report for vehicle

### ISSUE THREAD

**Issue by equareo** [skodaconnect/homeassistant-myskoda#212]
After running the service for some hours hours it ends up with a 429 and 24 hour ban. It always end with this exact get request getting 429. I've not done any toggles, just started the integration, and let it run. 

2024-11-08 07:41:15.220 DEBUG (MainThread) [myskoda.myskoda] Trace: GET https://mysmob.api.connect.skoda-auto.cz/api/v1/vehicle-heal - response: 429 (124 bytes) Too many requests occurred during getting warning lights report for vehicle {vinnumberremoved} and accept-language {en-US}.
2024-11-08 07:41:15.221 ERROR (MainThread) [myskoda.rest_api] Invalid status for GET request to /v1/vehicle-health-report/warning-lights/vinnumberremoved: 429
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 85, in _make_request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1121, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url='https://mysmob.api.connect.skoda-auto.cz/api/v1/vehicle-health-report/warning-lights/vinnumberremoved'
2024-11-08 07:41:15.224 ERROR (MainThread) [custom_components.myskoda.coordinator] Error fetching myskoda data: ('Error getting update from MySkoda API: %s', ClientResponseError(RequestInfo(url=URL('https://mysmob.api.connect.skoda-auto.cz/api/v1/vehicle-health-report/warning-lights/vinnumberremoved'), 

Car: Citigo

Here is a link to a long log:  [https://bin.68degrees.no/?acf71efcad3c395a#E33sNjb8p2MXjRNsCcpPh2Xy7uU1S5vGE7mcEo7Z5kbZ](https://bin.68degrees.no/?acf71efcad3c395a#E33sNjb8p2MXjRNsCcpPh2Xy7uU1S5vGE7mcEo7Z5kbZ)

**Comment by WebSpider** [comment]
Thanks for your report. The logfile contains useful information. 
We need to figure out what's happening and how to prevent this from happening. Looks like not a quick fix, unfortunately.

**Comment by dvx76** [comment]
At first sight I don't think this is specific to this particular endpoint (`api/v1/vehicle-health-report/...`). 

#189 makes the poll interval configurable. It will be available in the next version. Would be interesting, just as a test, to see if this still happens if the poll interval is bumped to, say, 1h.

If you have the full logs available you could maybe count the occurrence of the trace for any endpoint (might as well use this one), e.g.

```
grep -c "Trace: GET https://mysmob.api.connect.skoda-auto.cz/api/v1/vehicle-heal" homeassistant.log
```

Just to confirm the number of times we hit the API.

@WebSpider I don't think `aiohttp.ClientSession.request` has an build-in retries and I don't see any from our own code either so this really should just be the normal polling + any mqtt events, but those are debounced 🤔

**Comment by dvx76** [comment]
Actually instead of the count above maybe count the number of normal (every 30m) refreshes vs the triggerd refresh (on event)

```
grep -c "Updating full vehicle" homeassistant.log

grep -c "Performing scheduled update of all data for vin" homeassistant.log
```

**Comment by equareo** [comment]
> Actually instead of the count above maybe count the number of normal (every 30m) refreshes vs the triggerd refresh (on event)
> 
> ```
> grep -c "Updating full vehicle" homeassistant.log
> 
> grep -c "Performing scheduled update of all data for vin" homeassistant.log
> ```

First is 1, second is 43

**Comment by dvx76** [comment]
Thanks! So that is expected and well within reasonable bounds. The 1 is going to be the result of some event (e.g. car getting unlocked, staring to charge, etc) and the 43 are the normal refresh every 30m (so there would be 48 in a full day).

So really it looks like it is the backend of the `api/v1/vehicle-healh-status` endpoint for Citigo (and maybe other models) which has a much lower limit than some other backends.

Short-term fix and good improvement overall would be to just log a warning if we get a 429 and move along getting the other endpoints.

Long-term fix would be to implement per-endpoint intervals and debounce.

**Comment by equareo** [comment]
24 hours later i still get this error. I think it's dependent on the car being used. The counter is probably reset when the car is driven.

**Comment by dvx76** [comment]
#261 should at least avoid that these 429 for just one endpoint cause the complete integration to fail. I don't know if there's much more we can do in the integration for this?

**Comment by equareo** [comment]
> #261 should at least avoid that these 429 for just one endpoint cause the complete integration to fail. I don't know if there's much more we can do in the integration for this?

I updated to 1.9.1, but i still get the error, shouldn't that fix be in already?

**Comment by WebSpider** [comment]
Yes, should be in. Can you see if you can capture logs?

**Comment by equareo** [comment]
[https://bin.68degrees.no/?69e92dabdfc62371#2nGiGwFexr5HVkgi8L37kVkw3ryxboB9rYZAscUBMrrY](https://bin.68degrees.no/?69e92dabdfc62371#2nGiGwFexr5HVkgi8L37kVkw3ryxboB9rYZAscUBMrrY)

Here is a snippet from the log where it goes from getting info to getting stubborn :p hope that helps!

**Comment by dvx76** [comment]
Hmm yeah. @WebSpider I guess to make this work (that is, allow some endpoints to fail and still update HA with data from the endpoints that did work) we need to have `MySkoda.get_vehicle()` not raise an exception and instead leave the relevant Vehicle member(s) unset (in this case `Vehicle.health`)?

**Comment by WebSpider** [comment]
I think with #296 merged, we should no longer raise anything custom only exceptions that HA handles natively

**Comment by dvx76** [comment]
The problem here is that from HA to MySkoda it's a single call (`MySkoda.get_vehicle()`) so either we raise an exception, in which case no `Vehicle` object gets returned and HA can't update anything, or we don't :)

**Comment by WebSpider** [comment]
So we basically should handle the update as seperate calls in HA then. Shouldnt be a problem, we have seperate methods for the individual calls as well.

**Comment by dvx76** [comment]
> So we basically should handle the update as seperate calls in HA then

Either that, or we integration only raises an exception when, say, more than 2 endpoints fail. Of just one or two endpoints fail it returns a `Vehicle` with the fields corresponding to those endpoints being `None`.

**Comment by pmunck86** [comment]
I have the same issue with an Octavia from 2017. Don't know if this information helps somehow

**Comment by WebSpider** [comment]
We will be changing the `myskoda` library a bit so we can request only partial updates. 

Once that has been released, we can add logic to the integration to skip endpoints whenever we want, and we'll see what happens if we completely ignore the `vehicle-health-report` for CitigoE.

**Comment by ikaakkola** [comment]
Changing coordinator.py to:

```
        # Obtain vehicle data.
        try:
            _LOGGER.debug("Getting partial vehicle data")
            vehicle = await self.myskoda.get_partial_vehicle(
                self.vin,
                [
                    CapabilityId.ACCESS,
                    CapabilityId.AIR_CONDITIONING,
                    CapabilityId.AUXILIARY_HEATING,
                    CapabilityId.CHARGING,
                    CapabilityId.FUEL_STATUS,
                    CapabilityId.HONK_AND_FLASH,
                    CapabilityId.MEASUREMENTS,
                    CapabilityId.OUTSIDE_TEMPERATURE,
                    CapabilityId.PARKING_POSITION,
                    CapabilityId.STATE,
                    CapabilityId.TRIP_STATISTICS,
                    CapabilityId.VEHICLE_WAKE_UP
                ],
            )
```

fixes this for my vehicle.

I think there is some invalid retry logic somewhere for this error, causing blacklisting of client and resulting in "permanent" 429 response, but I'm not familiar enough with the implementation to figure out where that might be..

**Comment by WebSpider** [comment]
> Same problem with a MY2020 Skoda Karoq, running 1.16.0 , with update interval set to 60 minutes
> 
> Also as stated by @pmunck86 , when this happens the official MySkoda App also stops working, either it says "Unavailable" entirely, or when trying to enable auxiliary heater it ends up with the "Limit of battery protection reached" error.
> 
> From the logs it seems this endpoint is called very often (when an error happens?). 
> 

Thanks for this report. Would you mind opening a seperate issue for this? We have not seen this yet in a Karoq. Given that Karoq and CitigoE use different connectivity hardware, we might be dealing with a different problem.
