### ISSUE TITLE
Field "overall_average_travel_time_in_min" of type int is missing in TripStatistics instance

### ISSUE THREAD

**Issue by Tomanic-glitch** [skodaconnect/homeassistant-myskoda#219]
I get the following error when setting up my Kodiaq II with the updated v1.8.1

![missing](https://github.com/user-attachments/assets/5f2f2a0d-7cec-4753-a4cd-379a493f009f)

This error originated from a custom integration.

Logger: custom_components.myskoda.coordinator
Source: helpers/update_coordinator.py:382
integration: MySkoda (documentation, issues)
First occurred: 13:20:14 (1 occurrences)
Last logged: 13:20:14

Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 94, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 301, in get_vehicle
    vehicle.trip_statistics = await self.get_trip_statistics(vin)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 262, in get_trip_statistics
    return (await self.rest_api.get_trip_statistics(vin, anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 191, in get_trip_statistics
    result = self._deserialize(raw, TripStatistics.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 392, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "overall_average_travel_time_in_min" of type int is missing in TripStatistics instance

**Comment by WebSpider** [comment]
Thanks!

We will probably need a few more iterations for Kodiaq unless someone provides a fixture.
Fixing this in next release.

**Comment by Tomanic-glitch** [comment]
Thanks a lot! Is this the fixture you are looking for or is it something completely different?

[my_favorite_car.zip](https://github.com/user-attachments/files/17678697/my_favorite_car.zip)

**Comment by WebSpider** [comment]
Yes, it is. Can you make a PR to make it available for us to conduct tests against?

Example is here: https://github.com/skodaconnect/myskoda/pull/171

**Comment by Tomanic-glitch** [comment]
Ok great, hopefully I did this correctly
