### ISSUE TITLE
Failed setup: Field "statuses" of type list[CapabilityStatus] in Capability has invalid value ['INSUFFICIENT_SPIN']

### ISSUE THREAD

**Issue by HoffmannThomas** [skodaconnect/homeassistant-myskoda#233]
**Describe the bug**
Failure during integration setup for a 2024 Enyaq

**Debug logs**
`Traceback (most recent call last):
  File "<string>", line 8, in __mashumaro_from_dict_json__
  File "/usr/local/lib/python3.12/site-packages/myskoda/models/info.py", line 141, in drop_unknown_capabilities
    return [Capability.from_dict(c) for c in value if c["id"] in CapabilityId]
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 17, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "statuses" of type list[CapabilityStatus] in Capability has invalid value ['INSUFFICIENT_SPIN']`

**Installation:**
 - Home Assistant variant: Docker

**Comment by dvx76** [comment]
Thanks for your report. This should be fixed in the next release.
