### ISSUE TITLE
Add Parking Heater Ventilation Switch

### ISSUE THREAD

**Issue by WebSpider** [skodaconnect/homeassistant-myskoda#236]
This is a template issue from the project to get more SkodaConnect sensors into `homeassistant-myskoda`.

**Sensor**
Parking Heater Ventilation

**Last known status**
No support in MySkoda API's discovered yet

**Comment by prvakt** [comment]
Functionality is already implemented in [PR#226](https://github.com/skodaconnect/myskoda/pull/226).
Ventilation can be started via `start_auxiliary_heating()` using `startMode=VENTILATION`

I can probably also implement this switch once I finish the auxiliary heater which is in my opinion more important in these cold days 🧊

**Comment by prvakt** [comment]
is there anyone with only ventilation without parking heater?
