### ISSUE TITLE
Add Outside Temperature Sensor

### ISSUE THREAD

**Issue by WebSpider** [skodaconnect/homeassistant-myskoda#243]
This is a template issue from the project to get more SkodaConnect sensors into `homeassistant-myskoda`.

**Sensor**
Outside Temperature

**Last known status**
API's discovered in MySkoda.
Verify this is correct and then add to integration.

**Comment by prvakt** [comment]
is there anyone who can actually see outside temperature in official MySkoda app?

**Comment by AlexGuld** [comment]
In the old MySkoda essentials I had outside temperatur, so perhaps Skoda will add it again.
![Image](https://github.com/user-attachments/assets/346a3ec0-024d-4329-84d3-835555890a12)

**Comment by WebSpider** [comment]
Awesome find 👍

**Comment by WebSpider** [comment]
Support for getting the values is added in `myskoda` version `0.14.0`
We can add the sensor now.

**Comment by prvakt** [comment]
looks like its available only when `AUXILIARY_HEATING` and `OUTSIDE_TEMPERATURE` capabilities are present
