### ISSUE TITLE
Add Parking Heater Status

### ISSUE THREAD

**Issue by WebSpider** [skodaconnect/homeassistant-myskoda#244]
This is a template issue from the project to get more SkodaConnect sensors into `homeassistant-myskoda`.

**Sensor**
Parking Heater Status

**Last known status**
No support in MySkoda API's discovered yet

**Comment by prvakt** [comment]
#311

**Comment by WebSpider** [comment]
This has been released in v1.10.0 of the integration. Feel free to try it out!

**Comment by msandvold** [comment]
Hi.
Currently on version: 1.11.1
No Parking heater status are showing.

Skoda Superb MK3 2017/2018
