### ISSUE TITLE
Add Parking Light Status

### ISSUE THREAD

**Issue by WebSpider** [skodaconnect/homeassistant-myskoda#245]
This is a template issue from the project to get more SkodaConnect sensors into `homeassistant-myskoda`.

**Sensor**
Parking Light Status

**Last known status**
No support in MySkoda API's discovered yet

**Comment by Elle4u** [comment]
I think it is allready there. It is called "lights_on". It does not show the light-status, but the parking-light status (Skoda Enyaq).
So I translated it for german to "Parklicht" as it was in the other integration.

Not sure if I am right...

**Comment by WebSpider** [comment]
Thanks for this information! I will definately check this for my enyaq!

**Comment by Elle4u** [comment]
I will recheck, too.

**Comment by Elle4u** [comment]
I think, I have to overwork the translation-file, now?
