### ISSUE TITLE
Add Refuel Statistics

### ISSUE THREAD

**Issue by WebSpider** [skodaconnect/homeassistant-myskoda#247]
This is a template issue from the project to get more SkodaConnect sensors into `homeassistant-myskoda`.

**Sensor**
Refuel Statistics

**Last known status**
No support in MySkoda API's discovered yet

**Comment by prvakt** [comment]
I don't think this is available in MySkoda API.. new API provides only weekly, monthly and yearly statistics, but not since last refuel

**Comment by WebSpider** [comment]
If anyone has this available in Myskoda API, please provide screenshots

**Comment by horusfalke** [comment]
I'm interessted in this sensors, because I used it in the past.
I still have the old integration installed and it shows me the statistics.

**Comment by WebSpider** [comment]
If you have it available in the new app, please provide screenshots so we know where to start looking
