### ISSUE TITLE
Missing entities for Skoda Superb IV (compared to Skoda Connect).

### ISSUE THREAD

**Issue by XalaTheShepard** [skodaconnect/homeassistant-myskoda#255]
Dear all, 

First of all a huge thanks for creating a new component for the new Skoda app. 
I have to apologize for creating this issue.

My Skoda Superb IV Hybrid can only be loaded from time to time in HA (Core 2024.11.1) using this integration. 
When it is loaded, it only creates 2 unknown entities (main render of vehicle and software version).

In my logs I find the following 4 errors (side note, also still using the old Skoda Connect integration):

Logger: myskoda.rest_api
Source: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:394
First occurred: 3:39:27 PM (42 occurrences)
Last logged: 4:30:56 PM

Failed to deserialize data: {"carType":"gasoline","primaryEngineRange":{"engineType":"gasoline","currentSoCInPercent":88,"currentFuelLevelInPercent":88},"carCapturedTimestamp":"2024-11-09T03:48:52Z"}
Traceback (most recent call last):
  File "<string>", line 24, in __mashumaro_from_json__
  File "<string>", line 21, in __mashumaro_from_dict_json__
mashumaro.exceptions.MissingField: Field "remaining_range_in_km" of type int is missing in EngineRange instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 392, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 26, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "primary_engine_range" of type EngineRange in DrivingRange has invalid value {'engineType': 'gasoline', 'currentSoCInPercent': 88, 'currentFuelLevelInPercent': 88}

------------------------------------------

Logger: myskoda.rest_api
Source: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:394
First occurred: 4:32:28 PM (47 occurrences)
Last logged: 5:43:04 PM

Failed to deserialize data: {"vehicleType":"HYBRID","detailedStatistics":[{"date":"2024-11-11"},{"date":"2024-11-12"},{"date":"2024-11-13"},{"date":"2024-11-14"},{"date":"2024-11-15"},{"date":"2024-11-16"},{"date":"2024-11-17"}]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 392, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "overall_average_travel_time_in_min" of type int is missing in TripStatistics instance

---------------------------------------

This error originated from a custom integration.

Logger: custom_components.myskoda.coordinator
Source: helpers/update_coordinator.py:382
integration: MySkoda (documentation, issues)
First occurred: 4:32:28 PM (47 occurrences)
Last logged: 5:43:04 PM

Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 94, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 301, in get_vehicle
    vehicle.trip_statistics = await self.get_trip_statistics(vin)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 262, in get_trip_statistics
    return (await self.rest_api.get_trip_statistics(vin, anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 191, in get_trip_statistics
    result = self._deserialize(raw, TripStatistics.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 392, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "overall_average_travel_time_in_min" of type int is missing in TripStatistics instance

--------------------------------------------------

This error originated from a custom integration.

Logger: custom_components.myskoda.coordinator
Source: helpers/update_coordinator.py:382
integration: MySkoda (documentation, issues)
First occurred: 4:32:28 PM (47 occurrences)
Last logged: 5:43:04 PM

Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 94, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 301, in get_vehicle
    vehicle.trip_statistics = await self.get_trip_statistics(vin)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 262, in get_trip_statistics
    return (await self.rest_api.get_trip_statistics(vin, anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 191, in get_trip_statistics
    result = self._deserialize(raw, TripStatistics.from_json)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 392, in _deserialize
    data = deserialize(text)
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __mashumaro_from_json__
mashumaro.exceptions.MissingField: Field "overall_average_travel_time_in_min" of type int is missing in TripStatistics instance

Many thanks for having a look at theses issues, keeping the project alive and supporting all those vehicles. 

Kind regards, 

Robin

**Comment by WebSpider** [comment]
Can you please try this with v1.8.2

**Comment by XalaTheShepard** [comment]
I have installed v1.8.2 of My Skoda. Still only the same two entities as mentioned above show up. This time the main render of vehicle shows an image, but the software version is unavailable. 
So a little step forward, but not completely there. 
Is it possible this issue is caused because I still use the old Skoda Connect integration beside the new My Skoda integration? 

Many thanks for looking into this issue. 

If I can be of any assistance, please let me know. 

Kind regards, 

Robin

**Comment by dvx76** [comment]
@XalaTheShepard can you post any debug or errors you get in the logs with 1.8.2?

> Is it possible this issue is caused because I still use the old Skoda Connect integration beside the new My Skoda integration?

Should not be an issue. I've run both in parallel for a long time.

**Comment by WebSpider** [comment]
I think I know what's going on:

In v1.8.x we have limited the software version sensor to only show up when you have an electric vehicle (MEB platform), because so far we only know MEB platform actually has a software version. 

If an earlier version already has created the sensor, it will be abandoned, but not deleted.

You can probably delete the sensor manually, by selecting the sensor, going to properties and delete it.

**Comment by XalaTheShepard** [comment]
Dear WebSpider, that's a possibility and explains why it is always unavailable., However, I am still missing almost all entities. Dear dvx76, I will provide you with the logs this evening. Many thanks both for looking into this issue 🙂

**Comment by WebSpider** [comment]
If we have more logs, we can better figure out what's going on indeed.
In the mean time, have a look at https://github.com/orgs/skodaconnect/projects/1 to see if there are any sensors you expect that we simple have not added yet to the integration.

**Comment by XalaTheShepard** [comment]
Dear WebSpider and dear dvx76, after rebooting HA again now 27 entities showed up. 
I can assume the issue is solved. 

As mentioned above, these are the entities I am still missing which are available in Skoda Connect: 
- Lock entity for the doors
- Lock entity for the trunk
- Fuel level of my car
- Amount of KM I can drive with the current fuel level
- Amount of KM I can drive with the current battery level

Would it be possible to add these entities? The 3 entities I use the most are the device tracker, Fuel level and lock entity for the doors. 

Many thanks for all the support and love this project is receiving. 

Kind regards, 

Robin

**Comment by prvakt** [comment]
@XalaTheShepard : there is already work in progress for fuel level, and remaining combustion and electric range (PR #265)
