### ISSUE TITLE
Great job integrating Superb MK3 L&K 2017/2018 - missing some switches and sensors.

### ISSUE THREAD

**Issue by msandvold** [skodaconnect/homeassistant-myskoda#259]
GREAT JOB closing this "issue" https://github.com/skodaconnect/homeassistant-myskoda/issues/190

Integrationis now loading.
Missing the following options (compared to [skodaconnect](https://github.com/skodaconnect/homeassistant-skodaconnect) :
- switch.xxxx_force_data_refresh
- switch.xxxx_parking_heater_heating
- switch.xxxx_parking_heater_ventilation
- sensor.xxxx_outside_temperature
- sensor.xxxx_combustion_range
- sensor.xxxx_fuel_level
- switch.xxxx_start_flashing
- switch.xxxx_start_honking_and_flashing
- sensor.xxxx_last_trip_average_fuel_consumption
- sensor.xxxx_last_trip_average_speed
- sensor.xxxx_last_trip_duration
- sensor.xxxx_last_trip_length
- sensor.xxxx_service_inspection_days (my skoda shows hours instead of days)
- sensor.xxxx_service_inspection_distance
- sensor.xxxx_oil_inspection_days
- sensor.xxxx_oil_inspection_distance
- binary_sensor.xxxx_vehicle_moving
- sensor.xxxx_car_info (states VIN no and attributes: Engine and Model)
- individual sensors for open/closed doors and vindows.

That is all, so far :)

**Comment by WebSpider** [comment]
Thanks for your request!

Can you please look at https://github.com/orgs/skodaconnect/projects/1 and see if we missed anything?
Also, we do not seek exact parity with skodaconnect, as the API's are not the same and both Skoda and HA have evolved.

**Comment by msandvold** [comment]
Hi, @WebSpider
Thanks for Your reply, the ToDo list seem to cover my question, as the most "important" features are listed there.
Looks great :)
