### ISSUE TITLE
Expose all car image renders through integration

### ISSUE THREAD

**Issue by gschot** [skodaconnect/homeassistant-myskoda#282]
To create custom MySkoda app-like views of the car in a Home Assistant card, it would be useful to have all available car render urls delivered by the lib available in the integration as a text entities or attribute list with these urls.

**Comment by HairyPorter23** [comment]
Is it possible to get a small piece of code for how to make a dynamic picture depending on charging/not charging like in the Skoda App with these URL attributes? 😇

**Comment by gschot** [comment]
> Is it possible to get a small piece of code for how to make a dynamic picture depending on charging/not charging like in the Skoda App with these URL attributes? 😇

I ended up with taking the urls from the entity and placing them in a picture elements card. You can then show images conditionally. All images are transparent, so you can overlay the connected cable image. Show the grey cable when connected and no current, the green one when the charging power entity has some other value than 0.0. I even added the christmas decoration shown during the holiday season 😂
