### ISSUE TITLE
[Feature] localization

### ISSUE THREAD

**Issue by sonar98** [skodaconnect/homeassistant-myskoda#3]
It would be nice if the switches and sensors and its values have translations in different languages.

If the labels, etc. are added to the en.json in the translation folder the community can help with translating to different languages.

**Comment by WebSpider** [comment]
We are slowly adding translations into the mix, see https://github.com/skodaconnect/homeassistant-myskoda/pull/10

**Comment by WebSpider** [comment]
This has now been merged. Feel free to send PR's for languages. We may consider adding a translation service later on.
