### ISSUE TITLE
Translation Improvement: "Honk and Flash" and "Flash" (NL)

### ISSUE THREAD

**Issue by Youri3246** [skodaconnect/homeassistant-myskoda#301]
The translation to NL for "honk and flash" and "flash" isn't quite correct. They are literally translated. In my opinion, it should be:

Flash: "Gevarenlichten" 

Honk and flash: "Claxon en gevarenlichten"

**Comment by WebSpider** [comment]
If you want to contribute to the translations, feel free to join our Crowdin project (see README.md) or submit a PR

**Comment by Rocker20** [comment]
As I recall, the normal lights flash when you use honk and flash and not the “hazard lights” so them the translation is correct.
