### ISSUE TITLE
Range entity no longer working

### ISSUE THREAD

**Issue by TheMrBooyah** [skodaconnect/homeassistant-myskoda#302]
**Describe the bug**
Since the update to 1.9.0 I noticed I no longer have a valid range value.
I'm using the integration with my Skoda Enyaq IV

**Is this working in MySkoda app?***
Yes I can see the range in the MySkoda App

**Latest working release**
Pre 1.9.0

**Debug logs**
If applicable, add debug logs. Debug logs help us locate and fix a problem quicker

**Installation:**
Core: 2024.11.2
Supervisor: 2024.11.2
Operating System: 13.2
Frontend: 20241106.2

![image](https://github.com/user-attachments/assets/d0b8c8c8-511c-4adb-aec5-fa62f7df7295)

**Comment by WebSpider** [comment]
We'll need more logging since it is working on my Enyaq with 1.9.1

**Comment by TheMrBooyah** [comment]
[home-assistant_myskoda_2024-11-16T19-54-10.454Z.log](https://github.com/user-attachments/files/17788136/home-assistant_myskoda_2024-11-16T19-54-10.454Z.log)

Did enable debug logging but didn't see any errors to indicate anything going wrong. Removed VIN number and other unrelated log lines from other integrations.

**Comment by WebSpider** [comment]
Can you enable tracing as well, in the integration options (right next to the S-PIN)

**Comment by TheMrBooyah** [comment]
[home-assistant_myskoda_2024-11-16T22-50-58.236Z.log](https://github.com/user-attachments/files/17788196/home-assistant_myskoda_2024-11-16T22-50-58.236Z.log)
Should have all private information redacted. 
I did notice that I do get this information back in one of the API calls:
`"remainingCruisingRangeInMeters":224000`

**Comment by WebSpider** [comment]
Yes, it is, however since we support electric, hybrid and ice vehicles, we get the data from a different endpoint, but that endpoint i do not see queried in this log. Is the log complete? It would seem to miss a few endpoints

**Comment by TheMrBooyah** [comment]
This is everything I get in the logging. I stopped when I got a lot of:
`2024-11-17 00:12:52.098 DEBUG (MainThread) [myskoda.mqtt] Sending PINGREQ`
`2024-11-17 00:12:52.111 DEBUG (MainThread) [myskoda.mqtt] Received PINGRESP`

Mind telling me what endpoint you are expecting to see?

**Comment by dvx76** [comment]
Possibly related to #268 - range was changed to populate from driving_range instead of battery

**Comment by dvx76** [comment]
The driving_range endpoint is only queried if we see the `STATE` capability. From some of user-submitted fixtures I see that can be unavailable based on inactive subscriptions

```
      - id: STATE
        statuses:
        - LICENSE_MISSING
        - LICENSE_EXPIRED
```

So that is likely what is happening here.

I think maybe for the Range sensor we have it fall back to the range from  the battery data if the driving_range isn't available ?

**Comment by WebSpider** [comment]
Yeah, the car has the right capabilities and the license is missing, we can fall back indeed.
