### ISSUE TITLE
Integration stopped working - reinstallation not possible

### ISSUE THREAD

**Issue by hummermann87** [skodaconnect/homeassistant-myskoda#304]
Integration has stopped showing data for my Skoda Enyaq.
Updated to 1.9.1 - no change. Since today, no login/reinstallation possible - MySkoda Android app still works.
See log below.

_"Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.myskoda.config_flow
Quelle: custom_components/myskoda/config_flow.py:103
Integration: MySkoda (Dokumentation, Probleme)
Erstmals aufgetreten: 09:47:58 (2 Vorkommnisse)
Zuletzt protokolliert: 09:52:42

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/myskoda/config_flow.py", line 103, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/myskoda/config_flow.py", line 62, in validate_input
    await hub.connect(data["email"], data["password"])
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 120, in connect
    await self.authorization.authorize(email, password)
  File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 77, in authorize
    self.idk_session = await self._get_idk_session()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 222, in _get_idk_session
    authentication = await self._enter_password(login_meta)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/auth/authorization.py", line 165, in _enter_password
    raise TermsAndConditionsError(location)
myskoda.auth.authorization.TermsAndConditionsError: /signin-service/v1/7f045eee-7003-4379-9968-9355ed2adb06@apps_vw-dilab_com/terms-and-conditions?relayState=80960575eb5150e39011515f3fb4035852936fec&canChangeCountryOfResidence=true&userId=de7b5cc8-70d8-45f2-830c-4ef4aee0ebfd"_

**Comment by dvx76** [comment]
Please search issues first, there are now dozens of reported cases for the same thing: https://github.com/skodaconnect/homeassistant-myskoda/issues?q=%22terms-and-conditions%22

There are new terms and conditions to accept. You get prompted on login. To force this log out and then back in with the MySkoda mobile app and you will be prompted to accept the new T&C. After that the integration should work again.

**Comment by mvzut** [comment]
I had the same recently. What helped was to use another account, not from the my skoda domain but from vwgroup.io (somehow I had both in my password manager, no idea when I created those exactly to be honest). This gave me access again.

**Comment by unze** [comment]
I had the same issue, the fix was loggin in to Skoda Connect shop and accept the new terms and conditions:
https://shop.skoda-connect.com/
