### ISSUE TITLE
Aux heater not visible for Kodiaq

### ISSUE THREAD

**Issue by WebSpider** [skodaconnect/homeassistant-myskoda#321]
I have updated to v1.10.0 but don't see any new entity for the Auxiliary heater even if my Skoda Kodiaq is equipped with it and it's present in the Myskoda app as well as in the old Skoda Connect integration

![myskoda](https://github.com/user-attachments/assets/77220b60-d7b7-45a4-931e-998e4fb50dad)
![skoda-connect](https://github.com/user-attachments/assets/c4684486-d195-490e-bd4b-2a28d6ff32b6)
![version1 10 0](https://github.com/user-attachments/assets/00880f74-a21f-46d7-a5b6-5371af286c71)

_Originally posted by @Tomanic-glitch in https://github.com/skodaconnect/homeassistant-myskoda/pull/311#issuecomment-2483689130_

**Comment by rgjertsen** [comment]
I just have to ask. Are you guys talking about a parking heater or aux heater? If I'm not mistaking an aux heater is not turned on by the user. The option available in the old integration and Myskoda app is the parking heater.
In Projects I see it mentiones as parking heater, but aux heater everywhere else.
I also have a Kodiaq so I have the same issues.

**Comment by rgjertsen** [comment]
> Ah, i think there is a bit of misunderstanding.
> 
> In the app its called the parking heater. In the API its called the aux heater (basically, the heater which is not part of the AC)

Ok, if it is the heater the user can turn on while the car is parked it should be called a Parking Heater.
An aux heater, in my opinion, is a heater that turns on automatically while the motor is running. So not something the user can control themselves. 
The translation should in this case also be changed to Parking Heater.

**Comment by dvx76** [comment]
Aligning with terminology used in the MySkoda app makes sense. That will be the reference point for most users.

**Comment by Tomanic-glitch** [comment]
Interesting, when I check the MySkoda app it's called Auxiliary heater there.

![Auxiliary_heater](https://github.com/user-attachments/assets/b23b0e18-5ed9-4dca-b295-b21087bbe045)

**Comment by rgjertsen** [comment]
> Interesting, when I check the MySkoda app it's called Auxiliary heater there.
> 
> ![Auxiliary_heater](https://private-user-images.githubusercontent.com/61036575/387598609-b23b0e18-5ed9-4dca-b295-b21087bbe045.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMTEzMzUsIm5iZiI6MTczMjAxMTAzNSwicGF0aCI6Ii82MTAzNjU3NS8zODc1OTg2MDktYjIzYjBlMTgtNWVkOS00ZGNhLWIyOTUtYjIxMDg3YmJlMDQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDEwMTAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNjFhY2E4NTU2Njk4ZGVhNWEwMjJkODg0M2VmMjFmNzZmODU2NDJkZTA0YmM4ZTI1MTYyMmUwZWZmYmJjMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.V8xywhQGqM1c6gsM9Q1XNdWQ0yEAoIdnh1uYSVcVb3k)

Interesting. In my app for my Kodiaq it is called Parking Heater, only translated of course.
I am talking about the heater for the AC, though. To be sure we are talking about the same thing. 
It looks similar, only I can choose Heating or Ventilation and I can't choose the temperature remotely.

**Comment by prvakt** [comment]
@rgjertsen can you please change language inside your app (you can find it under profile tab) and check it afterwards. 
I expect they use "Auxiliary Heater" in english but maybe translated as Parking Heater into your language... I don't think Skoda has some other heater than this one (just with different configuration options for different cars)

**Comment by rgjertsen** [comment]
> @rgjertsen can you please change language inside your app (you can find it under profile tab) and check it afterwards. I expect they use "Auxiliary Heater" in english but maybe translated as Parking Heater into your language... I don't think Skoda has some other heater than this one (just with different configuration options for different cars)
> 
> and fyi this is how it looks inside my app (Superb iV) ![IMG_20241119_112053](https://private-user-images.githubusercontent.com/74157307/387604417-203703c7-67a7-4316-9e16-23a2fbba11a7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMTI5OTAsIm5iZiI6MTczMjAxMjY5MCwicGF0aCI6Ii83NDE1NzMwNy8zODc2MDQ0MTctMjAzNzAzYzctNjdhNy00MzE2LTllMTYtMjNhMmZiYmExMWE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDEwMzgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZTI3MWQ4ZTFmNDVhMDdhZWNiOTcyZTVjY2RmOWE3YzgxZmQ0Y2JlNmEwYWJhZjM4NWRlYzlhMTY1MTcyYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.camEgatfsF7542TJ6EusEXguebZAPVprshVj3CbsJ-M)

You are correct. It is called Auxiliary Heater in english and that is translated to Parkeringsvarmer, which is Parking Heater, in norwegian. The picture is from the new MySkoda app and the car is a Kodiaq.
![IMG_9761](https://github.com/user-attachments/assets/7993c105-6ba2-43f4-aec2-0a60a7ecb76a)

**Comment by prvakt** [comment]
So I suggest to stick with "Auxiliary Heater" in english for now so its matching the name in MySkoda app.

**Comment by rgjertsen** [comment]
> So I suggest to stick with "Auxiliary Heater" in english for now so its matching the name in MySkoda app.

I agree. The important part is that we are talking about the same heater.
I have changed the translation for my language so I'm happy :)

**Comment by rgjertsen** [comment]
I see this is marked Complete without a new update.
Also @prvakt mentioned an update was already in the works.
Should this stay Open until the update is released?

**Comment by rgjertsen** [comment]
Any news on the status for this bug?
After 1.12 it is still not available for combustion Kodiaq.

**Comment by prvakt** [comment]
PR #368 is ready, please wait until it gets merged into main or feel free to test my branch
