### ISSUE TITLE
Precondition failed - login failure

### ISSUE THREAD

**Issue by Lrputola** [skodaconnect/homeassistant-myskoda#326]
There seems to a lot of login issues lately. Everything worked out just fine until this morning 11 a.m. CET. Integration fails to log in to API.

Yes, I have updated the Terms and Services and it did work ok for a while. Tried to log in to Skoda Store and also to skoda.vwgroup.io. I do get in and all the permissions are fine. Myskoda app works otherwise fine and is able to update car status (Skoda Enyaq 2023), but if I want to check my account in the app, it raises an error "Unexpected error, try again later".

This is what I see in integration logs. Sorry that some parts are in Finnish, but I believe you get the idea.

Tämä virhe on peräisin mukautetusta integroinnista.

`
Lokikirjaaja: custom_components.myskoda
Lähde: custom_components/myskoda/__init__.py:55
integraatio: MySkoda (dokumentaatio, ongelmat)
Ensimmäistä kertaa ilmennyt: 17.25.10 (5 tapahtumat)
Viimeksi kirjattu: 18.05.03

Login with MySkoda failed for an unknown reason.
Traceback (most recent call last):
  File "/config/custom_components/myskoda/__init__.py", line 55, in async_setup_entry
    await myskoda.connect(config.data["email"], config.data["password"])
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 124, in connect
    user = await self.get_user()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 296, in get_user
    return (await self.rest_api.get_user(anonymize=anonymize)).result
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 239, in get_user
    data=await self._make_get_request(url),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 96, in _make_get_request
    return await self._make_request(url=url, method="GET")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 86, in _make_request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1158, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 412, message='Precondition Failed', url='https://mysmob.api.connect.skoda-auto.cz/api/v1/users'
`

`Lokikirjaaja: myskoda.rest_api
Lähde: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:92
Ensimmäistä kertaa ilmennyt: 17.25.10 (5 tapahtumat)
Viimeksi kirjattu: 18.05.03

Invalid status for GET request to /v1/users: 412
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 86, in _make_request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1158, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 412, message='Precondition Failed', url='https://mysmob.api.connect.skoda-auto.cz/api/v1/users'`

And at some point it gave this warning at the same exact time. Not sure if it's related.

`Lokikirjaaja: homeassistant
Lähde: runner.py:147
Ensimmäistä kertaa ilmennyt: 17.25.11 (4 tapahtumat)
Viimeksi kirjattu: 17.54.31

Error doing job: Unclosed client session (None)`

**Comment by WebSpider** [comment]
I saw this one while troubleshooting something else. This happens when your S-PIN is incorrect.

**Comment by Lrputola** [comment]
Thanks! I'll look into it.

**Comment by Lrputola** [comment]
Just a short report that the issue I am encountering might be related to MySkoda app. I can't change the S-PIN code there after recent change I made and somehow it is all messed up now. In any case this points to direction, that you are absolutely right, Webspider. I reported this to Skoda and their technical team is looking into it. Report back when it is sorted and the cause is known.

**Comment by WebSpider** [comment]
Thank you for the error message. We will add some handling so you get a more to the point notification

**Comment by nils512** [comment]
i have the same issue - also on the android app.
It seems like, that Skoda have an issue:
https://allestörungen.de/stoerung/skoda-connect/
![grafik](https://github.com/user-attachments/assets/3ef6edb8-5ad4-4408-a325-003c00809a1b)

**Comment by dvx76** [comment]
VW WE Connect shows almost the same graph. As @Farfar reminds us every year, during the first colder weeks of the year there are always issues as people start using the app to preheat their cars 🙈 

@WebSpider you want to keep this open to improve the error message correct?

**Comment by nils512** [comment]
skoda is back online :-)

**Comment by Lrputola** [comment]
Ok, same here. Skoda is back online. This had most to do with their system and very little with this very nice integration. Thanks for pointing out the issue! I'm confindent it made the job for the Skoda IT-ppl much easier.
