### ISSUE TITLE
Skoda Superb IV door lock - unable to lock or unlock doors

### ISSUE THREAD

**Issue by XalaTheShepard** [skodaconnect/homeassistant-myskoda#332]
Dear all,

I am currently using version 1.9.1 of the MySkoda integration.
In this version the lock entity for the doors has been added.
However, this lock entity remains unavailable for my Skoda Superb IV, whereas I can use this function in the Skoda Connect integration.
I am running HA Core 2024.11.2 in a HassOS setup.

If any questions, please do not hesitate to contact me. 

Kind regards,

Robin

**Comment by WebSpider** [comment]
Enter your S-PIN in the integration configuration and the lock will become available

**Comment by XalaTheShepard** [comment]
Many thanks for the swift reply. Hadn't looked there yet 🙂
