### ISSUE TITLE
Charge limit on Superb IV

### ISSUE THREAD

**Issue by kiteman44** [skodaconnect/homeassistant-myskoda#336]
It is impossible to change the charge limit on Superb IV. I saw PR #178 and installed version 1.7.2. I also have "unknow" value like issue #166. In the integration "https://github.com/skodaconnect/homeassistant-skodaconnect" it is a numeric value in ampere but on this integration it is a value in %. In the new MySkoda application, I can change the charge limit (max or reduced).

Do you think it is possible to put this functionality back by modifying?

**Comment by dvx76** [comment]
#178 just disables entities which are specific to MEB cars (like Enyaq) on cars which are not (like Suberb iV).

I think setting charge limit and/or power for Suberb iV and similar cars is just not implemented yet. I can't find an existing issue tracking that so we can use this one for that purpose.

> but on this integration it is a value in %

Where do you see that? You might be mixing up charge limit (in %, defining up to what SoC to charge) and charge power (how fast to charge, I believe indeed in Amps on MQB/hybrid models like Suberb iV, and just a boolean reduced/not-reduced on MEB/Enyaq)

**Comment by prvakt** [comment]
just looks like they have unified the parameters between PHEV and EV

In old API it was possible to set `value=1-255 or "Maximum" or "Reduced"` 

PHEV were using 1-255 where 252 was used for reduced and 254 for max
EV were using only "Maximum" or "Reduced"

Now only Maximum/Reduced is supported in the request.. I have already tried to send a number but I got invalid response

**Comment by kiteman44** [comment]
Thanks prvakt and dvx76 for your answer

prvakt, you are right ;)

Hope they add this "old" functionnality it's  convenient to charge with my solar panels ;)

**Comment by prvakt** [comment]
yeah, I'm also missing this functionality as I have solar panels too and I was utilizing my charging as much as possible from sun :) 

in case it will appear in new API in future (even I doubt about that ), I will implement it into this integration ASAP ;)

**Comment by kiteman44** [comment]
👍 thanks

**Comment by prvakt** [comment]
yes this can be closed as there is nothing we can do because of API not supporting this feature
