### ISSUE TITLE
Vehicle moving sensor

### ISSUE THREAD

**Issue by fatsi01** [skodaconnect/homeassistant-myskoda#339]
Would it be possible to add a sensor to state if the vehicle is moving. 

You are using an integration that is still in development. 
This integration currently only supports the MySkoda API compatible with the MySkoda App.

We have no intention to support features not in the MySkoda App, for instance the Skoda Essentials app.

**Please search issues in https://github.com/skodaconnect/myskoda and https://github.com/skodaconnect/homeassistant-myskoda for duplicates or fixes before reporting a new feature request.**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dvx76** [comment]
Hi @fatsi01 , the device tracker should show `vehicle_in_motion` when it's moving (and the matching HA location name when it's not moving and the position is known).

See also #206 and #234
