### ISSUE TITLE
Vehicle status render

### ISSUE THREAD

**Issue by prvakt** [skodaconnect/homeassistant-myskoda#342]
Would be great if we can retrieve render of vehicle status as well.

Render needs to be retrieved trough MySkoda API with `HTTP GET` using full path from `get_status()` response -> /`renders`/`light_mode` or `dark_mode`/`one_x` or `one_and_half_x` or `two_x` or `three_x` depending on required size. threeX is the biggest one with size 888x1338px in my case

For example `HTTP GET` `https://mysmob.api.connect.skoda-auto.cz/api/v2/vehicle-status/render?carType=COMBI&vehicleState=1-1-3-1-0-0-0-0-0&lastModifiedAt=1730291332&dimension=3x&theme=LIGHT` -> where response is PNG image like the one below
![image](https://github.com/user-attachments/assets/388343ac-6a19-4123-b473-1589bc51dc0b)

**Comment by WebSpider** [comment]
Ah, you did an actual request, that was on my todo list. Good to know it will show you the actual state as png!

**Comment by WebSpider** [comment]
I've been tinkering with this one a bit. 
The main challenge is to obtain the image inside the clientsession of the library, that way we are authentication-proof.
