### ISSUE TITLE
Missing switch: Skoda Citigo iV - Start Electric Climatisation

### ISSUE THREAD

**Issue by jakobkragelund** [skodaconnect/homeassistant-myskoda#344]
Great with a new integration! Thanks for your work.

My Skoda Citigo does not show a switch to start climatisation. It only shows switch for charging. It is not shown as a climate entity either.

Skoda CitigoE iV 
Firmware (from essentials API): 2020-03-12
Hardware (from this integration): Hardware: NE13E2-2020

Screenshot of switches is from old integration

Feature is available in MySkoda app.

![IMG_5219](https://github.com/user-attachments/assets/b46ca28f-11dd-4662-b88d-17c9c1642ec8)
![Citigo](https://github.com/user-attachments/assets/73af65a2-c86c-469b-b145-b8e1755eaaff)

**Comment by prvakt** [comment]
would it be possible to generate fixtures for your car? Most likely your car is using different capability than used in other cars and that's the reason why the climate switch is not visible in your HA

**Comment by dvx76** [comment]
To extend on what @prvakt is asking, you can find the instructions here: https://github.com/skodaconnect/myskoda?tab=readme-ov-file#as-cli 

If you're unable to do that what would also probably help is debug (https://github.com/skodaconnect/homeassistant-myskoda?tab=readme-ov-file#enable-debug-logging) + tracing (it's an option in the HA UI when configuring the MySkoda integration) logs covering at least one full data pull (by default every 30m).

**Comment by prvakt** [comment]
any success with fixtures generation? if not, maybe you can wait until my PR #345 is approved and released with new version of this integration and afterwards you will be able to generate fixtures very easily with button press in HA

**Comment by jakobkragelund** [comment]
Fixtures has been generated in a venv, but my linux skills are so lame, that I haven't found the file in my filesystem yet. Working on that. Will debug logs help because I have those.

PR 345 will be a great help for me!!

**Comment by github-Jan** [comment]
I have genereated fixtures for the Citigo iV
[citigo.zip](https://github.com/user-attachments/files/17923133/citigo.zip)

**Comment by jakobkragelund** [comment]
> I have genereated fixtures for the Citigo iV [citigo.zip](https://github.com/user-attachments/files/17923133/citigo.zip)

From my knowledge, there is a difference between citigos produced before and after 7/2020. Mine is 03/2020, so it might behave differently than yours.

Are you also missing the start climate in your HA?

**Comment by prvakt** [comment]
> > I have genereated fixtures for the Citigo iV [citigo.zip](https://github.com/user-attachments/files/17923133/citigo.zip)
> 
> From my knowledge, there is a difference between citigos produced before and after 7/2020. Mine is 03/2020, so it might behave differently than yours.
> 
> Are you also missing the start climate in your HA?

new version of this integration is available (`v1.11.0`) with `Generate Fixture` button, so if possible, please contribute your fixtures here as well.. At least I can compare if there is any difference between

**Comment by prvakt** [comment]
#357 this PR should fix your problem and enable AC for Citigo iV

**Comment by github-Jan** [comment]
> > I have genereated fixtures for the Citigo iV [citigo.zip](https://github.com/user-attachments/files/17923133/citigo.zip)
> 
> From my knowledge, there is a difference between citigos produced before and after 7/2020. Mine is 03/2020, so it might behave differently than yours.
> 
> Are you also missing the start climate in your HA?

I thought that all the Citigo/up/Mii hat same HW (apart from the missing DAB radio) so feel free to check if your fixtures are different from my car.

I was missing some capabilities that were in the old app, but not the new ones. but the charging timeplans (?) do not seem to be available in the new app (and the fixture) at all :-/

**Comment by jakobkragelund** [comment]
[Citigo_jakkra.zip](https://github.com/user-attachments/files/17939507/Citigo_jakkra.zip)
Fixtures generated for citigoE produced in 3/2020

Should i upload somewhere else also?

**Comment by prvakt** [comment]
@jakobkragelund I will take care, thanks!

**Comment by jakobkragelund** [comment]
> @jakobkragelund I will take care, thanks!

Thanks so much for your work!

**Comment by WebSpider** [comment]
This is available in v1.12.0
