### ISSUE TITLE
Add departure timers

### ISSUE THREAD

**Issue by squrppi** [skodaconnect/homeassistant-myskoda#346]
As a charging automation user, I would like to have departure timers settings available, so that I can automatically set charging parameters based on car location. My car is Skoda Superb IV.

Use case:
- If my car is at home, I toggle Departure Timer 3 on and set cheap price times, so that charging happens during night when electricity is at its cheapest.
- If my car is not at home, I toggle Departure Timer 3 off, so that it will start charging immediately if connected to a commercial charger on the road.

This works with the old integration. Now switching to the new one, I would like to continue my current automation.

**Comment by prvakt** [comment]
Its on my todo list as soon as I will implement whole auxiliary heating logic and AC configuration settings into HA.. 

to have it here as well, `HTTP POST` `v1/vehicle-automatization/{vin}/departure/timers`

Request structure
```
{
    "deviceDateTime": "2024-11-06T20:40:15.287+01:00",
    "timers": [
        {         
            "id": 1,
            "enabled": true,
        }
    ]
}
```

`id` = `1`, `2` or `3`
`enabled` = `true` or `false`
