### ISSUE TITLE
Polling interval in seconds instead of minutes 

### ISSUE THREAD

**Issue by benjamin-dcs** [skodaconnect/homeassistant-myskoda#352]
**Describe the solution you'd like**
Be able to configure the polling rate of a car/entry in seconds in stead of minutes to get updates quicker for cars that do not send mqtt messages. 

Relates to https://github.com/skodaconnect/homeassistant-myskoda/issues/234

**Comment by WebSpider** [comment]
Please use the `homeassistant.update_entity` service, combined with an automation if you need to update this often. Please know that updating this often 24/7 will likely get you banned from MySkoda api

**Comment by WebSpider** [comment]
You can find more information on how to use the `homeassistant.update_entity` service at https://github.com/skodaconnect/homeassistant-myskoda?tab=readme-ov-file#disabling-polling
