### ISSUE TITLE
REST API bug when configuring the integration

### ISSUE THREAD

**Issue by LasseHedeby** [skodaconnect/homeassistant-myskoda#36]
I get an error after I have configured the integration. It seems that some key/value pairs is missing in the response from my car.

From log:
Logger: myskoda.rest_api
Kilde: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:43
Første forekomst: 21.24.44 (7 forekomster)
Senest logget: 21.29.22

Failed to load data from url /v1/charging/TMBJC9NY5MFremoved. Return value was '{"isVehicleInSavedLocation":false,"status":{"chargingRateInKilometersPerHour":0.0,"chargePowerInKw":0.0,"remainingTimeToFullyChargedInMinutes":0,"battery":{"remainingCruisingRangeInMeters":194000,"stateOfChargeInPercent":43}},"settings":{"targetStateOfChargeInPercent":80,"preferredChargeMode":"MANUAL","availableChargeModes":["MANUAL"],"chargingCareMode":"ACTIVATED","autoUnlockPlugWhenCharged":"OFF","maxChargeCurrentAc":"MAXIMUM","batterySupport":"DISABLED"},"carCapturedTimestamp":"2024-09-26T18:19:57Z","errors":[{"type":"STATUS_OF_CHARGING_NOT_AVAILABLE","description":"Status of charging is not available."}]}'
Traceback (most recent call last):
  File "<string>", line 24, in __mashumaro_from_json__
  File "<string>", line 14, in __mashumaro_from_dict_json__
mashumaro.exceptions.MissingField: Field "state" of type ChargingState is missing in ChargingStatus instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 26, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "status" of type Optional[ChargingStatus] in Charging has invalid value {'chargingRateInKilometersPerHour': 0.0, 'chargePowerInKw': 0.0, 'remainingTimeToFullyChargedInMinutes': 0, 'battery': {'remainingCruisingRangeInMeters': 194000, 'stateOfChargeInPercent': 43}}

**Comment by LasseHedeby** [comment]
Could this be the issue in the myskoda python library?
![image](https://github.com/user-attachments/assets/d679ca97-0e1f-4138-a62f-45b16ad36f0f)

Should line 92 in myskoda/models/charging.py be
`state: ChargingState | None`

**Comment by WebSpider** [comment]
Indeed, we dont have this one yet, we'll add it and update the library.

In the mean time, did you do anything special to arrive at this state?

**Comment by LasseHedeby** [comment]
Thnx

No I did not. My app is reporting the same error. But I cannot get it to disappear.

**Comment by LasseHedeby** [comment]
It is planned for charging to night so I will check tomorrow to see if it has disappeared.

**Comment by LasseHedeby** [comment]
This morning after my car had charged the error disappeared and I got in HA
![image](https://github.com/user-attachments/assets/fc6de561-1a79-4c07-8e8c-cd993c7430ab)
![image](https://github.com/user-attachments/assets/f13d9cc1-56c4-4401-bea7-096231256ee5)
