### ISSUE TITLE
Refactor coordinator._on_charging_event function

### ISSUE THREAD

**Issue by fursov** [skodaconnect/homeassistant-myskoda#370]
Currently the function does following steps:
1. checks if `vehicle.charging` and `vehicle.charging.status` contain data
    - updates the status if it is not available, otherwise
    - updates the data to `vehicle.charging.status` with the data received from `change-soc` event
2. checks if `vehicle.driving_range` contains data
    - updates vehicle.driving_range if it is not available, otherwise
    - updates data to vehicle.driving_range from received change-soc event
3. updates vehicle using `set_updated_vehicle(vehicle)`

The flow is a bit suboptimal, partially because `update_charging()` and `update_driving_range()` implicitly call `set_updated_vehicle(vehicle)` inside so step 3 becomes redundant. Another drawback is having two places where event type should be analysed (in both step 1 and 2).

The flow should be following:
1. check if `vehicle.charging` and `vehicle.charging.status` contain data
    - if not, then call `update_charging()` and exit the function, because `update_charging()` will handle the vehicle update
2. check if `vehicle.driving_range` contains data
    - if not then call `update_driving_range()`, do not exit, proceed to 3
3. create match-case for the received event type
    - if it is `change-soc` - update data in all required structures and call `set_updated_vehicle(vehicle)`
    - if it is `charging-status-changed`, then call `update_charging()` since the event does not contain data, we need to have it updated explicitly

Other charging events can be added later if needed because currently I have no good understanding when those are fired.

**Comment by WebSpider** [comment]
> Currently the function does following steps:
> 
> 1. checks if `vehicle.charging` and `vehicle.charging.status` contain data
>    
>    * updates the status if it is not available, otherwise
>    * updates the data to `vehicle.charging.status` with the data received from `change-soc` event
> 2. checks if `vehicle.driving_range` contains data
>    
>    * updates vehicle.driving_range if it is not available, otherwise
>    * updates data to vehicle.driving_range from received change-soc event
> 3. updates vehicle using `set_updated_vehicle(vehicle)`
> 
> The flow is a bit suboptimal, partially because `update_charging()` and `update_driving_range()` implicitly call `set_updated_vehicle(vehicle)` inside so step 3 becomes redundant. Another drawback is having two places where event type should be analysed (in both step 1 and 2).
> 
> The flow should be following:
> 
> 1. check if `vehicle.charging` and `vehicle.charging.status` contain data
>    
>    * if not, then call `update_charging()` and exit the function, because `update_charging()` will handle the vehicle update

No, not entirely. 
It could very well be that the car has not updated towards MySkoda yet, I see this with my Enyaq quite a bit, where the car is asleep, charging, and emits `change-soc` events. If you poll for data, you will get older data than the mqtt message.

So we should either:

1- Fetch data via `update_charging()` and enhance this with data from mqtt OR
2- Fetch daa via `update_charging()`, see which one is most recently obtained from the car, and let that one survive

> 2. check if `vehicle.driving_range` contains data
>    
>    * if not then call `update_driving_range()`, do not exit, proceed to 3
> 3. create match-case for the received event type
>    
>    * if it is `change-soc` - update data in all required structures and call `set_updated_vehicle(vehicle)`
>    * if it is `charging-status-changed`, then call `update_charging()` since the event does not contain data, we need to have it updated explicitly
> 
> Other charging events can be added later if needed because currently I have no good understanding when those are fired.

Agreed.
