### ISSUE TITLE
NS73N5-2022 (Kodiaq) not giving any entities

### ISSUE THREAD

**Issue by pieterdevriesch** [skodaconnect/homeassistant-myskoda#381]
**Describe the bug**

After installing the integration and restarting, I logged in with my SkodaID and the integration is loaded. However it only shows 2 entities: Generate Fixtures and Main Render of Vehicle (which is correct, the VIN is also shown on the integration screen, it seems to have the right car). I am missing all of the entities with information about the car. I tried restarting multiple times, no change.

**Is this working in MySkoda app?***

MySkoda app is working normally.

**Debug logs**

If I click Generate Fixtures then this error shows up in the logs after a short while:

> Logger: myskoda.rest_api
> Source: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:100
> First occurred: 15:53:50 (7 occurrences)
> Last logged: 15:54:00
> 
> Invalid status for GET request to /v2/air-conditioning/TMXXXXXXXXXXXXXX/auxiliary-heating: 429
> Invalid status for GET request to /v1/vehicle-health-report/warning-lights/TMXXXXXXXXXXXXXX: 500
> Invalid status for GET request to /v1/charging/TMXXXXXXXXXXXXXX: 429
> Invalid status for GET request to /v2/vehicle-status/TMXXXXXXXXXXXXXX/driving-range: 429
> Invalid status for GET request to /v1/trip-statistics/TMXXXXXXXXXXXXXX?offsetType=week&offset=0&timezone=Europe%2FBerlin: 500
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 94, in _make_request
>     response.raise_for_status()
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1158, in raise_for_status
>     raise ClientResponseError(
> aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://mysmob.api.connect.skoda-auto.cz/api/v2/vehicle-status/TMXXXXXXXXXXXXXX'

**Installation:**
 - Home Assistant 2024.11.3
 - HACS install of integration

The old integration did indeed stop working today as predicted, which is why I am switching over.

**Comment by WebSpider** [comment]
The '429' error means you are temporarily rate-limited by MySkoda

**Comment by pieterdevriesch** [comment]
Thanks for the info. It's weird though, this happened right after the installation and the old integration was also limited (and no longer working). Maybe because it stopped working it started spamming the API? Anyway I'll wait a couple of days and come back with an update. I assume it will keep trying automatically?

**Comment by WebSpider** [comment]
> Thanks for the info. It's weird though, this happened right after the installation and the old integration was also limited (and no longer working). Maybe because it stopped working it started spamming the API? Anyway I'll wait a couple of days and come back with an update. I assume it will keep trying automatically?

You are in uncharted territory when apps quit functioning, so i cant answer that properly.

I do know that when you restart the integration (or re-enable it), it will ask MySkoda again for the state of your car and create entities for the capabilities it sees.

**Comment by pieterdevriesch** [comment]
Thanks for the guidance, I've kept the integration disabled for a few days and today, also a few updates later, I've enabled it again and it has now loaded the entities. So problem solved, hopefully a one time thing.
