### ISSUE TITLE
Ventilation function not working (Superb 3 MK2024)

### ISSUE THREAD

**Issue by pawelaugustyn** [skodaconnect/homeassistant-myskoda#398]
**Describe the bug**
Auxiliary heater ventilation function does not work on Superb 3 FL MK2024. The climate entity exposes only two modes: `off` and `heat`. I believe there should be third mode: `fan_only`.

<details><summary>Click to show the picture</summary>

![image](https://github.com/user-attachments/assets/f5ffe3f6-8535-4349-a9b9-51df8d5c329f)
![image](https://github.com/user-attachments/assets/c7dbdfdf-44ae-4d63-b9f4-9358aab2f957)

</details>

**Is this working in MySkoda app?***
Yes, it is.

**Latest working release**
1.14.0

**Debug logs**

All fixtures from my car (enabled heater, enabled ventilation, disabled heater) are available here https://github.com/skodaconnect/homeassistant-myskoda/issues/385

**Installation:**
 - Home Assistant variant: Docker 2024.11.3

**Additional context**

**Comment by prvakt** [comment]
@pawelaugustyn: thanks for your report, your car doesn't have `ACTIVE_VENTILATION` capability and that's the reason why is not visible in your HA instance. Can you please confirm auxiliary heating is working now? 

If you want to make a quick test with ventilation, please modify `/homeassistant/custom_components/myskoda/climate.py`
replace all `ACTIVE_VENTILATION` occurrences with `AUXILIARY_HEATING_BASIC` (line 243 and line 271) and restart HA. Would be great to let me know if it worked for you.

Just a note for myself: looks like Skoda decided to change capability for ventilation from `ACTIVE_VENTILATION` to `AUXILIARY_HEATING_BASIC` so I will include this capability as well

**Comment by pawelaugustyn** [comment]
Yes, it worked after changing these two lines.
<details><summary>Picture</summary>

| HA | MySkoda |
| - | - |
| <img width="349" alt="image" src="https://github.com/user-attachments/assets/e4691960-cb22-431a-bf3a-6b6beb959d93"> | <img width="349" alt="image" src="https://github.com/user-attachments/assets/93d30b6b-617b-43d9-9fd5-e7ec0e725a0c"> |

</details>

**Comment by prvakt** [comment]
@pawelaugustyn excelent! thank you ;) you can keep it like this, I will update the code so next version will work with ventilation without additional changes

**Comment by pawelaugustyn** [comment]
> you can keep it like this

That's exactly what I plan to do :p Thank you for your efforts to make this integration work flawlessly! 🚀
