### ISSUE TITLE
Outside temperature sensor showing incorrect value

### ISSUE THREAD

**Issue by Tomanic-glitch** [skodaconnect/homeassistant-myskoda#404]
It seems that the new Outside Temperature sensor in v1.14.1 is giving wrong value compared to the old Skoda Connect integration for my Skoda Kodiaq II.

Myskoda:
![Myskoda](https://github.com/user-attachments/assets/94ce592e-0340-41f8-91ea-a0a1e75c9723)

Skoda Connect:
![Skoda_connect](https://github.com/user-attachments/assets/fdc08a27-0089-4d36-992a-556c5e69f380)

**Comment by WebSpider** [comment]
> It seems that the new Outside Temperature sensor in v1.14.1 is giving wrong value compared to the old Skoda Connect integration for my Skoda Kodiaq II.
> 
> Myskoda: ![Myskoda](https://private-user-images.githubusercontent.com/61036575/392429969-94ce592e-0340-41f8-91ea-a0a1e75c9723.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjQ0NDIsIm5iZiI6MTczMzMyNDE0MiwicGF0aCI6Ii82MTAzNjU3NS8zOTI0Mjk5NjktOTRjZTU5MmUtMDM0MC00MWY4LTkxZWEtYTBhMWU3NWM5NzIzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE0NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZWQ3ZWI5ZmIyYmJkMGM1YmUyM2RkMTEzNWU1YjZhN2M1N2RlYTBhODViNzEyMTVkN2YyMWUxMTNjZmM4NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.17JYaGl9roEs-zLBe-Bom3dVjX1RJlV5VQCOt-2_p98)
> 
> Skoda Connect: ![Skoda_connect](https://private-user-images.githubusercontent.com/61036575/392429974-fdc08a27-0089-4d36-992a-556c5e69f380.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjQ0NDIsIm5iZiI6MTczMzMyNDE0MiwicGF0aCI6Ii82MTAzNjU3NS8zOTI0Mjk5NzQtZmRjMDhhMjctMDA4OS00ZDM2LTk5MmEtNTU2YzVlNjlmMzgwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE0NTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NTQyMDViZDQwMzNkMGJmZDk5MGIzNjAxNzA3NDVlZjVjYzBhMmNiNzRhZjM0OWM0NWRiNjk0OWQyYjQ2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tq5Fzz-n-whRDF9nfLnmgSI5qAz1CwM_8vOlmDbeStI)
> 

What does it show in the MySkoda app?

**Comment by Tomanic-glitch** [comment]
As far as I know this value is not shown in MySkoda app at all.

**Comment by prvakt** [comment]
@Tomanic-glitch can you generate fixtures and check what temperature is returned? You can copy fixtures here if you want and I will check it for you.  I would expect this value is really coming from auxiliary-heating response as we are not processing or converting this field ..

**Comment by prvakt** [comment]
yeah I think Skoda needs to fix some problems on their side heh.. there is nothing we can do now

**Comment by WebSpider** [comment]
We could add some bounds checking. 
I think it is safe to assume anything between say -50C and 60C is a valid temperature on earth, anything else is bogus and should preferrably not result in a sensor update.

**Comment by prvakt** [comment]
@WebSpider: yeah that can solve problem with absolute zero :) but for example my car is reporting 6 degrees since yesterday 09:44, so I think there is still some work to do from Skoda side.

**Comment by Tomanic-glitch** [comment]
Seems like it was a temporary problem as the temperature sensor in MySkoda integration now reports correct values

![Outside_temperature](https://github.com/user-attachments/assets/109d708a-6600-4dc1-83c1-0ee9a1a51248)

**Comment by dvx76** [comment]
Reported in Kelvin? 0C = 273K

**Comment by rds76** [comment]
I'm reading wrong temperature today as well, it was ok yesterday
![image](https://github.com/user-attachments/assets/f021cd5f-e597-423d-8587-8b70ad316bdb)

**Comment by prvakt** [comment]
I'm guessing its still in development from Skoda as its not yet available in MySkoda apk, just returned from their API

**Comment by rds76** [comment]
btw, how sensor update works, today I turned on aux heating with car keys and got it updated in HA in 30min. Are there any events from skoda servers or I need to set update interval to some small value?

**Comment by prvakt** [comment]
I have observed same.. When using my key to start heating, there is no event send to MQTT from car so we don't know about start-auxiliary-heating event. And because of that we don't know there is some operation in progress and just doing regular update

**Comment by prvakt** [comment]
When you start any operation from MySkoda app (or our integration), there is a request send to the car and on MQTT we receive back the progress events (started, in-progress, completed, etc.) And based on these events we can update those sensors.. But if there is nothing, we don't know that something has changed

**Comment by rds76** [comment]
Undesrtand, but I'm quite sure it was working in older `skodaconnect` integration. Will check if Skoda app reflects events from key or scheduled heating

**Comment by dvx76** [comment]
The old integration had a much lower default poll interval. The new one defaults to 30m but you can lower it as low as 1m if you want.

**Comment by dvx76** [comment]
Do we need to keep this open? If the API _sometimes_ returns an odd value (Kelvin instead of Celsius?) that's probably not something we want to deal with in the integration and would expect is fixed in the API. We just report what the API returns.

**Comment by WebSpider** [comment]
> Do we need to keep this open? If the API _sometimes_ returns an odd value (Kelvin instead of Celsius?) that's probably not something we want to deal with in the integration and would expect is fixed in the API. We just report what the API returns.

I'll add bounds checking for the entity, so useless values get ignored while MySkoda solves their API value issues
