### ISSUE TITLE
Report fixtures via HA diagnostics

### ISSUE THREAD

**Issue by dvx76** [skodaconnect/homeassistant-myskoda#411]
See if we can use https://www.home-assistant.io/integrations/diagnostics/ to make it easier for users to report fixtures

**Comment by WebSpider** [comment]
This looks very doable, looks like all we need to do is add generating fixtures to an override of `async_get_device_diagnostics`

**Comment by prvakt** [comment]
Made some tests on my place and seems its working.. Need to play with text formatting a little but I can implement it.
Just a question - in case of multiple vehicles - there is separate coordinator for each one?

**Comment by prvakt** [comment]
#415
