### ISSUE TITLE
Heating motor vehicles ( petrol/diesel) running time

### ISSUE THREAD

**Issue by JanKraslice** [skodaconnect/homeassistant-myskoda#427]
With the addition of version 1.14.1, it is possible to turn on heating or ventilation in vehicles, but there is a big problem with the time duration setting! 
By turning it on via Home assistant, the default time is set to minutes and cannot be changed. When switching on via the Myskoda app it is possible to set the time in 5 minute intervals up to 60 minutes see pictures. 

The set time is remembered by the vehicle and the next time the heating/ventilation is switched on it is always switched on to the last set time and this set time is the default for switching on with the remote control heater. So if I switch on just once via HomeAssistant the time is changed for the next switch on by any other means :-( 

Without this timeline, the heater is inadequate for 15 minutes for a diesel heater in winter and an outside temperature of around 0 degrees will not warm the vehicle sufficiently. In the My Skoda app I start the heater heating for 60 minutes then when I get to the car I turn it off any other time is not enough. Is it possible to adjust for me it is sufficient just to change the default 15 minutes to the maximum possible 60 minutes.

The photo sent is with the app we pity I turn on the ventilation as part of the tests and display the time.

Přidáním do verze 1.14.1 je možné ve vozidlech zapnout topení nebo větrání, ale je zde velký problém a to nastavení trvání času! 
Zapnutím přes Home assistant je výchozí čas nastaven na minut a nejde změnit. Při zapínání přes aplikaci Myskoda je možné nastavit čas po 5 minutových intervalech až po 60 minut viz obrázky. 

Nastavený čas si vozidlo pamatuje a při dalším spuštění topení / větrání je vždy zapnuto na poslední nastavenou hodnotu a tento nastavený čas je výchozí i pro zapnutí dálkovým ovladačem topení. Pokud tedy zapnu jen jedenkrát přes HomeAssistant je tím čas změněn i pro následující zapnutí jakýmkoliv jiným způsobem :-( 

Bez této časové osy je topení nedostatečné 15 minut u naftového topení v zimě a venkovní teplotě kolem 0 stupňů vozidlo dostatečně neohřeje. V aplikaci My Škoda spouštím topení ohřev na 60 minut následně po příchodu do vozu jej vypnu jakýkoliv jiný čas je málo. Je možné přizpůsobit za mě je dostatečné jen změnit výchozích 15 minut na maximální možných 60 minut.

Zaslané foto je s aplikace my škoda zapínám větrání v rámci testů a zobrazení času.
![Screenshot_20241209_165956_Mykoda](https://github.com/user-attachments/assets/7b20db84-a5be-4d1a-b50f-e20182bfff92)
![Screenshot_20241209_170056_Mykoda](https://github.com/user-attachments/assets/65140cb0-d069-47de-a434-557166e4ef9b)
![Screenshot_20241209_170202_Mykoda](https://github.com/user-attachments/assets/618ddfc1-a773-43e0-9d28-f97c2a926e76)

**Comment by prvakt** [comment]
And FYI you need to set your value before starting heater as duration is send in the request to start heating / ventilation

![image](https://github.com/user-attachments/assets/171deb78-379e-4e3d-8307-f2525ce5cd17)
![image](https://github.com/user-attachments/assets/4bb147bf-61f5-46f7-b273-d9827a499b54)

**Comment by WebSpider** [comment]
Thanks for the detail in your issue! 👍

**Comment by JanKraslice** [comment]
Hi, you were right and I overlooked the setting.
Sorry for the unnecessary query - report 
The heating time is adjustable, I have tested and the heating control is functional both on and off the same goes for ventilation
