### ISSUE TITLE
v.1.4.1: Cannot add Enyaq RS SUV MY25 (was working with 1.2)

### ISSUE THREAD

**Issue by Marianp90** [skodaconnect/homeassistant-myskoda#44]
Hi,
I was using the integration without issues since version 1.2.x.
All further updates do not work.
Find beneath the logs:

>Protokolldetails (FEHLER)
Logger: myskoda.rest_api
Quelle: /usr/local/lib/python3.12/site-packages/myskoda/rest_api.py:43
Erstmals aufgetreten: 17:59:01 (22 Vorkommnisse)
Zuletzt protokolliert: 18:15:43
>
>Failed to load data from url /v2/garage/vehicles/VIN?connectivityGenerations=MOD1&connectivityGenerations=MOD2&connectivityGenerations=MOD3&connectivityGenerations=MOD4. Return value was '{"vin":"VIN","name":"Enyaq","workshopModeEnabled":false,"licensePlate":"xxx","state":"ACTIVATED","devicePlatform":"WCAR","softwareVersion":"5.0","specification":{"title":"Škoda Enyaq","manufacturingDate":"2024-08-22","model":"Enyaq","modelYear":"2025","body":"SUV","trimLevel":"RS","systemCode":"UNKNOWN","systemModelId":"5AZJR4","maxChargingPowerInKW":125,"battery":{"capacityInKWh":77},"engine":{"type":"iV","powerInKW":250},"gearbox":{"type":"E1A"}},"renders":[{"url":"https://ip-modcwp.azureedge.net/modcwp5azv25100003/8X8X9NwpXysK5u4Dz-UcS370i_ZEqGMFtzuf4bxLJPX-5MIWPryhXAtaDnLjRfF1dv-TL6x1cAHF9K0OCs3.q-CEA-1920658dayvext_side1080.png?v=638604202250000000","viewPoint":"garage_l","type":"REAL","order":0},{"url":"https://ip-modcwp.azureedge.net/modcwp5azv25100003/8X8X9NwpXysK5u4Dz-UcS370i_ZEqGMFtzuf4bxLJPX-5MIWPryhXAtaDnLjRfF1dv-TL6x1cAHF9K0OCs3.q-CEA-700390dayvext_front1080.png?v=638604202250000000","viewPoint":"main","type":"REAL","order":1}],"compositeRenders":[],"capabilities":{"capabilities":[{"id":"ACCESS","statuses":[]},{"id":"AUTOMATION","statuses":[]},{"id":"BATTERY_CHARGING_CARE","statuses":[]},{"id":"BATTERY_SUPPORT","statuses":[]},{"id":"CHARGING_PROFILES","statuses":[]},{"id":"CHARGING_STATIONS","statuses":[]},{"id":"DEALER_APPOINTMENT","statuses":["INITIALLY_DISABLED"]},{"id":"DIGICERT","statuses":[]},{"id":"MAP_UPDATE","statuses":[]},{"id":"MEASUREMENTS","statuses":[]},{"id":"PARKING_INFORMATION","statuses":[]},{"id":"PARKING_POSITION","statuses":[]},{"id":"PLUG_AND_CHARGE","statuses":[]},{"id":"POI_SEARCH","statuses":[]},{"id":"ROADSIDE_ASSISTANT","statuses":[]},{"id":"ROUTING","statuses":[]},{"id":"STATE","statuses":[]},{"id":"TRAFFIC_INFORMATION","statuses":[]},{"id":"VEHICLE_HEALTH_INSPECTION","statuses":[]},{"id":"WARNING_LIGHTS","statuses":[]},{"id":"AIR_CONDITIONING_TIMERS","statuses":[]},{"id":"PREDICTIVE_WAKE_UP","statuses":[]},{"id":"AIR_CONDITIONING_SMART_SETTINGS","statuses":[]},{"id":"POWERPASS_TARIFFS","statuses":[]},{"id":"AIR_CONDITIONING_SAVE_AND_ACTIVATE","statuses":[]},{"id":"CUBIC","statuses":[]},{"id":"SUBSCRIPTIONS","statuses":[]},{"id":"DESTINATIONS","statuses":[]},{"id":"CHARGING_MEB","statuses":[]},{"id":"VEHICLE_SERVICES_BACKUPS","statuses":[]},{"id":"EV_ROUTE_PLANNING","statuses":[]},{"id":"CHARGE_MODE_SELECTION","statuses":[]},{"id":"DIGICERT","statuses":[]},{"id":"VEHICLE_HEALTH_WARNINGS","statuses":[]},{"id":"PAY_TO_PARK","statuses":[]},{"id":"ONLINE_SPEECH_GPS","statuses":[]},{"id":"GUEST_USER_MANAGEMENT","statuses":[]},{"id":"SERVICE_PARTNER","statuses":[]},{"id":"WINDOW_HEATING","statuses":[]},{"id":"ROUTE_IMPORT","statuses":[]},{"id":"CHARGING","statuses":[]},{"id":"AIR_CONDITIONING","statuses":[]},{"id":"EXTENDED_CHARGING_SETTINGS","statuses":[]},{"id":"VEHICLE_WAKE_UP_TRIGGER","statuses":[]},{"id":"ROUTE_PLANNING_10_CHARGERS","statuses":[]}]},"errors":[{"type":"MISSING_RENDER","description":"Getting render of view point {exterior_side} for vehicle VIN {VIN} failed with message {404 Not Found from GET http://render-service/api/v1/renders/VIN}"}]}'
Traceback (most recent call last):
  File "<string>", line 15, in __mashumaro_from_dict__
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
>ValueError: 'INITIALLY_DISABLED' is not a valid CapabilityStatus
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "<string>", line 8, in __mashumaro_from_dict_json__
  File "/usr/local/lib/python3.12/site-packages/myskoda/models/info.py", line 106, in drop_unknown_capabilities
    return [Capability.from_dict(c) for c in value if c["id"] in CapabilityId]
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 17, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "statuses" of type list[CapabilityStatus] in Capability has invalid value ['INITIALLY_DISABLED']
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "<string>", line 30, in __mashumaro_from_json__
  File "<string>", line 10, in __mashumaro_from_dict_json__
mashumaro.exceptions.InvalidFieldValue: Field "capabilities" of type list[Capability] in Capabilities has invalid value [{'id': 'ACCESS', 'statuses': []}, {'id': 'AUTOMATION', 'statuses': []}, {'id': 'BATTERY_CHARGING_CARE', 'statuses': []}, {'id': 'BATTERY_SUPPORT', 'statuses': []}, {'id': 'CHARGING_PROFILES', 'statuses': []}, {'id': 'CHARGING_STATIONS', 'statuses': []}, {'id': 'DEALER_APPOINTMENT', 'statuses': ['INITIALLY_DISABLED']}, {'id': 'DIGICERT', 'statuses': []}, {'id': 'MAP_UPDATE', 'statuses': []}, {'id': 'MEASUREMENTS', 'statuses': []}, {'id': 'PARKING_INFORMATION', 'statuses': []}, {'id': 'PARKING_POSITION', 'statuses': []}, {'id': 'PLUG_AND_CHARGE', 'statuses': []}, {'id': 'POI_SEARCH', 'statuses': []}, {'id': 'ROADSIDE_ASSISTANT', 'statuses': []}, {'id': 'ROUTING', 'statuses': []}, {'id': 'STATE', 'statuses': []}, {'id': 'TRAFFIC_INFORMATION', 'statuses': []}, {'id': 'VEHICLE_HEALTH_INSPECTION', 'statuses': []}, {'id': 'WARNING_LIGHTS', 'statuses': []}, {'id': 'AIR_CONDITIONING_TIMERS', 'statuses': []}, {'id': 'PREDICTIVE_WAKE_UP', 'statuses': []}, {'id': 'AIR_CONDITIONING_SMART_SETTINGS', 'statuses': []}, {'id': 'POWERPASS_TARIFFS', 'statuses': []}, {'id': 'AIR_CONDITIONING_SAVE_AND_ACTIVATE', 'statuses': []}, {'id': 'CUBIC', 'statuses': []}, {'id': 'SUBSCRIPTIONS', 'statuses': []}, {'id': 'DESTINATIONS', 'statuses': []}, {'id': 'CHARGING_MEB', 'statuses': []}, {'id': 'VEHICLE_SERVICES_BACKUPS', 'statuses': []}, {'id': 'EV_ROUTE_PLANNING', 'statuses': []}, {'id': 'CHARGE_MODE_SELECTION', 'statuses': []}, {'id': 'DIGICERT', 'statuses': []}, {'id': 'VEHICLE_HEALTH_WARNINGS', 'statuses': []}, {'id': 'PAY_TO_PARK', 'statuses': []}, {'id': 'ONLINE_SPEECH_GPS', 'statuses': []}, {'id': 'GUEST_USER_MANAGEMENT', 'statuses': []}, {'id': 'SERVICE_PARTNER', 'statuses': []}, {'id': 'WINDOW_HEATING', 'statuses': []}, {'id': 'ROUTE_IMPORT', 'statuses': []}, {'id': 'CHARGING', 'statuses': []}, {'id': 'AIR_CONDITIONING', 'statuses': []}, {'id': 'EXTENDED_CHARGING_SETTINGS', 'statuses': []}, {'id': 'VEHICLE_WAKE_UP_TRIGGER', 'statuses': []}, {'id': 'ROUTE_PLANNING_10_CHARGERS', 'statuses': []}]
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 41, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "<string>", line 32, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "capabilities" of type Capabilities in Info has invalid value {'capabilities': [{'id': 'ACCESS', 'statuses': []}, {'id': 'AUTOMATION', 'statuses': []}, {'id': 'BATTERY_CHARGING_CARE', 'statuses': []}, {'id': 'BATTERY_SUPPORT', 'statuses': []}, {'id': 'CHARGING_PROFILES', 'statuses': []}, {'id': 'CHARGING_STATIONS', 'statuses': []}, {'id': 'DEALER_APPOINTMENT', 'statuses': ['INITIALLY_DISABLED']}, {'id': 'DIGICERT', 'statuses': []}, {'id': 'MAP_UPDATE', 'statuses': []}, {'id': 'MEASUREMENTS', 'statuses': []}, {'id': 'PARKING_INFORMATION', 'statuses': []}, {'id': 'PARKING_POSITION', 'statuses': []}, {'id': 'PLUG_AND_CHARGE', 'statuses': []}, {'id': 'POI_SEARCH', 'statuses': []}, {'id': 'ROADSIDE_ASSISTANT', 'statuses': []}, {'id': 'ROUTING', 'statuses': []}, {'id': 'STATE', 'statuses': []}, {'id': 'TRAFFIC_INFORMATION', 'statuses': []}, {'id': 'VEHICLE_HEALTH_INSPECTION', 'statuses': []}, {'id': 'WARNING_LIGHTS', 'statuses': []}, {'id': 'AIR_CONDITIONING_TIMERS', 'statuses': []}, {'id': 'PREDICTIVE_WAKE_UP', 'statuses': []}, {'id': 'AIR_CONDITIONING_SMART_SETTINGS', 'statuses': []}, {'id': 'POWERPASS_TARIFFS', 'statuses': []}, {'id': 'AIR_CONDITIONING_SAVE_AND_ACTIVATE', 'statuses': []}, {'id': 'CUBIC', 'statuses': []}, {'id': 'SUBSCRIPTIONS', 'statuses': []}, {'id': 'DESTINATIONS', 'statuses': []}, {'id': 'CHARGING_MEB', 'statuses': []}, {'id': 'VEHICLE_SERVICES_BACKUPS', 'statuses': []}, {'id': 'EV_ROUTE_PLANNING', 'statuses': []}, {'id': 'CHARGE_MODE_SELECTION', 'statuses': []}, {'id': 'DIGICERT', 'statuses': []}, {'id': 'VEHICLE_HEALTH_WARNINGS', 'statuses': []}, {'id': 'PAY_TO_PARK', 'statuses': []}, {'id': 'ONLINE_SPEECH_GPS', 'statuses': []}, {'id': 'GUEST_USER_MANAGEMENT', 'statuses': []}, {'id': 'SERVICE_PARTNER', 'statuses': []}, {'id': 'WINDOW_HEATING', 'statuses': []}, {'id': 'ROUTE_IMPORT', 'statuses': []}, {'id': 'CHARGING', 'statuses': []}, {'id': 'AIR_CONDITIONING', 'statuses': []}, {'id': 'EXTENDED_CHARGING_SETTINGS', 'statuses': []}, {'id': 'VEHICLE_WAKE_UP_TRIGGER', 'statuses': []}, {'id': 'ROUTE_PLANNING_10_CHARGERS', 'statuses': []}]}
`

**Comment by dvx76** [comment]
Fixed in skodaconnect/myskoda#40 but not released yet

**Comment by WebSpider** [comment]
Released in 1.4.2
