### ISSUE TITLE
Setup of sensor platform myskoda is taking over 10 seconds (resulting in slow HA startup

### ISSUE THREAD

**Issue by arjanvroege** [skodaconnect/homeassistant-myskoda#444]
**Describe the bug**
Setup of sensor platform myskoda is taking over 10 seconds.

Logger: homeassistant.bootstrap
Source: bootstrap.py:1065
First occurred: 16:31:12 (1 occurrences)
Last logged: 16:31:12

Setup timed out for bootstrap waiting on {<Task pending name='Task-496' coro=<MySkodaDataUpdateCoordinator._mqtt_connect() running at /config/custom_components/myskoda/coordinator.py:177> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove()]>} - moving forward

**Latest working release**
not sure, seen this already of couple of versions

**Installation:**
 - Home Assistant variant: HassOS

**Additional context**

**Comment by WebSpider** [comment]
Yeah, we are seeing MQTT not wanting to connect, causing this to slow down.
I am looking for the correct way to let HA connect to MQTT once it has started.

Thanks for the report. We're working on it.

**Comment by WebSpider** [comment]
This should be fixed in 1.15.3 release

**Comment by dvx76** [comment]
Fixed in 1.15.3
