### ISSUE TITLE
Add new consumption sensors for CNG engines

### ISSUE THREAD

**Issue by WebSpider** [skodaconnect/homeassistant-myskoda#455]
There will be one more update comming in order to show remaining range for gas and combustion separatelly. Right know you probably have only range sensor combining these 2... 

In future we are planning to introduce also consumption sensors - may I know what unit is used for gas consumption? Is it kg/100km or l/100km ?

_Originally posted by @prvakt in https://github.com/skodaconnect/homeassistant-myskoda/issues/429#issuecomment-2540781135_

**Comment by prvakt** [comment]
still on my todo list :) would you like to add those sensors or can I take care about that?

**Comment by WebSpider** [comment]
The issue is just so that your private todo list does not stay private, and it's clear this is on our radar :+1: 
Feel free to pick this up as you see fit.

**Comment by sonar98** [comment]
Skoda mentions kg/100km on their site for CNG: 

![afbeelding](https://github.com/user-attachments/assets/93b1e77c-2e5f-4bf4-8ffc-d56d29d81f0e)
