### ISSUE TITLE
Citigo-e: mileage no longer available

### ISSUE THREAD

**Issue by pencoe** [skodaconnect/homeassistant-myskoda#458]
Sensor "mileage" only delivers "unknown". 

Last working version: 1.14.2 (because the 1.15.x was never announced as an update i jumped to 1.15.3 from this)

Home Assistant 2024.12.3
MySkoda 1.15.3
Language: german

**Comment by WebSpider** [comment]
We have made a change in v1.15 because the way we were requesting data was causing CitigoE to enter battery protection mode. This is an unintended side-effect from that change #431

**Comment by pencoe** [comment]
will Mileage come back or is this someting we have to live with? 

Can't say how much it sucks that VAG (Skoda, SEAT, VW) does not offer a stable, documented API to their cars. I really appreciate that there are brave people like you that reverse engineer the communication between the App(s) and the appropriate server: an extra big THANKS to you and all contributors! ❤️

**Comment by WebSpider** [comment]
It will be back in v1.16.1

**Comment by WebSpider** [comment]
Please update to v1.16.1
