### ISSUE TITLE
Main Render of Vehicle stoped working after last update.

### ISSUE THREAD

**Issue by dateles** [skodaconnect/homeassistant-myskoda#461]
After the last update the Main Render of Vehicle stopped to worked for my Enyaq Coupe, it was working well before. Reloaded the integration and still doesnt work.

**Debug logs**
There is no error logs

**Installation:**
 - Home Assistant variant: Hass OS 14.0 (Core 2024.12.3, Supervisor 2024.12)
 - Python library versions ["python3 -m pip list"]

**Comment by WebSpider** [comment]
What version are you running? We fixed this in #456 and released in `v1.16.0`

**Comment by WebSpider** [comment]
Duplicate of #448

**Comment by sonar98** [comment]
I'm using 1.16.0 and no image visible in my HA as well

**Comment by dateles** [comment]
I just updated to 1.16.0 and still no image
![image](https://github.com/user-attachments/assets/0a78317e-140c-48c0-b123-14979aae1208)
![image](https://github.com/user-attachments/assets/3d00db09-9e1c-41ec-87db-5d26829aa61e)

**Comment by sonar98** [comment]
fixed with #463

**Comment by WebSpider** [comment]
Please update to v1.16.1
