### ISSUE TITLE
Add Vehicle_Moving sensor like there is in the VW integration

### ISSUE THREAD

**Issue by wexman** [skodaconnect/homeassistant-myskoda#471]
I would like to be able to see whether or not the vehicle is currently moving. There is such a sensor in the VW integration, so my guess is that it should also be available for Skoda...

**Comment by gschot** [comment]
The device tracker entity goes to a 'vehicle_in_motion' state when the car is in motion.

**Comment by wexman** [comment]
Ah, ok. That should somehow be convertable into a binary sensor, right?

**Comment by sonar98** [comment]
you can use a helper to create a binary sensor based on the state

**Comment by wexman** [comment]
Thank you very much!
