### ISSUE TITLE
Add some data analysis from old API (Essentials app)

### ISSUE THREAD

**Issue by BartVPL** [skodaconnect/homeassistant-myskoda#474]
**IMPORTANT NOTE**

You are using an integration that is still in development. 
This integration currently only supports the MySkoda API compatible with the MySkoda App.

We have no intention to support features not in the MySkoda App, for instance the Skoda Essentials app.

**Please search issues in https://github.com/skodaconnect/myskoda and https://github.com/skodaconnect/homeassistant-myskoda for duplicates or fixes before reporting a new feature request.**

**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
Hi Team,
At the very begging I'd like to thank you for all your contribution and development of these integration. 
In previous one connected with old API and old Essentials app on mobile, there were few data than can be pulled from regarding actual combustion, long term combustion etc. from which you can create and check the charts in home assistant. 
I would like to ask for such opportunity in this integration as well - of course if API will allow to check these data.

**Describe alternatives you've considered**

**Additional context**

**Comment by prvakt** [comment]
There is similar issue already created https://github.com/skodaconnect/homeassistant-myskoda/issues/165

And there is plan to add statistics into our new integration, unfortunately new API doesn't provide statistics since last refuel like old API. New API provide only weekly, monthly and annual statistics.
