### ISSUE TITLE
Outside Temperature sensor unknown

### ISSUE THREAD

**Issue by Youri3246** [skodaconnect/homeassistant-myskoda#475]
**Describe the bug**

Outside temperature sensor value unknown.

**Latest working release**

I had the outside temperature sensor working in the old Skoda Connect integration.

**Comment by Youri3246** [comment]
Okey ! here is the file!

[myskoda-01JEYM9RTCB9W3BSJ8WYW29C7F-Škoda Scala-bc21373aee5fe6925d46be5c675e7a84.json](https://github.com/user-attachments/files/18202205/myskoda-01JEYM9RTCB9W3BSJ8WYW29C7F-Skoda.Scala-bc21373aee5fe6925d46be5c675e7a84.json)

**Comment by prvakt** [comment]
> Okey ! here is the file!
> 
> [myskoda-01JEYM9RTCB9W3BSJ8WYW29C7F-Škoda Scala-bc21373aee5fe6925d46be5c675e7a84.json](https://github.com/user-attachments/files/18202205/myskoda-01JEYM9RTCB9W3BSJ8WYW29C7F-Skoda.Scala-bc21373aee5fe6925d46be5c675e7a84.json)

Thanks! Looks like I was right - there is no outsideTemperature returned in API response from MySkoda.... Unfortunatelly there is nothing we can do - probably Skoda will add this feature for your car later as its still quite new feature and for example MySkoda app is not showing this information yet.
