### ISSUE TITLE
Does the polling wakes up the car

### ISSUE THREAD

**Issue by querdenker2k** [skodaconnect/homeassistant-myskoda#480]
In the readme is the notice that the polling can be configured. but what happens while polling? Will the car be wake up?
As well the description for automatic updates when the car send some updates... how does the code get the updates? via polling or will it receive push events?
I am asking because last week was my 12v battery of my enyaq empty. it must be powered externally to start.

**Comment by prvakt** [comment]
polling is done from MySkoda API and not from the car itself - it just means how often it will update data from MySkoda servers..
Wakeup is not done via our integration so problem with your battery was definitely not caused by our integration

**Comment by querdenker2k** [comment]
Great, thank you for the quick info
