### ISSUE TITLE
Electric car range goes to 0 (instead of unknown) during driving, version 1.4.5

### ISSUE THREAD

**Issue by EDelsman** [skodaconnect/homeassistant-myskoda#77]
**Describe the bug**
The range of the electric car should probably be unavailable while driving, but instead it reports 0. The screenshot shows the device tracker too, to show the 0 coincides with driving.

**Is this working in MySkoda app?***
Did dot check (driving ;-) )

**Latest working release**
If the problem started after updating to a new release, please state latest working release.

**Debug logs**
If applicable, add debug logs. Debug logs help us locate and fix a problem quicker

**Installation:**
 - Home Assistant variant: HAOS version 2024.10.1
 - Python version (when running Core or Supervised) [e.g. 3.7, 3.8]
 - Python library versions ["python3 -m pip list"]

**Additional context**
![IMG_0893](https://github.com/user-attachments/assets/ddc5a59a-9a77-4a7e-b805-eccf6339661d)

**Comment by mbrackjr** [comment]
I see the same behavior; v1.42 did **not** drop down to zero but gave a chart downwards as expected while driving.

**Comment by WebSpider** [comment]
Thanks for this report. Is there anything in your HA logs regarding this?

**Comment by dvx76** [comment]
I can see this too. The value is not actually 0 but the correct range off by 3 decimals (my range is 370, I get 0.37). Also not only while the vehicle is moving, for me at least. Hoping to take a look later today.
