### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by johnvanderster** [skodaconnect/homeassistant-myskoda#84]
**Describe the bug**
After installation, restart, add integration and login this error: 
Field "charger_lock_state" of type Optional[ChargerLockedState] in AirConditioning has invalid value 'INVALID'

**Is this working in MySkoda app?***
NA I think. App working.

**Latest working release**
Fresh install 1.45

**Debug logs**
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.myskoda.coordinator
Bron: helpers/update_coordinator.py:354
integratie: MySkoda (documentatie, problemen)
Eerst voorgekomen: 18:44:45 (21 gebeurtenissen)
Laatst gelogd: 19:09:30

Unexpected error fetching myskoda data
Traceback (most recent call last):
  File "<string>", line 62, in __mashumaro_from_json__
  File "/usr/local/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'INVALID' is not a valid ChargerLockedState

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/coordinator.py", line 82, in _async_update_data
    vehicle = await self.myskoda.get_vehicle(self.vin)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 239, in get_vehicle
    vehicle.air_conditioning = await self.get_air_conditioning(vin)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/myskoda.py", line 197, in get_air_conditioning
    return await self.rest_api.get_air_conditioning(vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 68, in get_air_conditioning
    return await self._make_get_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myskoda/rest_api.py", line 42, in _make_get_request
    data = deserialize(response_text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 64, in __mashumaro_from_json__
mashumaro.exceptions.InvalidFieldValue: Field "charger_lock_state" of type Optional[ChargerLockedState] in AirConditioning has invalid value 'INVALID'

**Installation:**
 - Home Assistant variant: Raspberry 4, Core 10.1, Supervisor 10.0

**Additional context**
-

**Comment by WebSpider** [comment]
Thanks for this report. What car is connected to your account?

**Comment by johnvanderster** [comment]
Ah, sorry. A 2024 PHEV Skoda Kodiaq II

**Comment by dvx76** [comment]
@WebSpider what should we map this to? We can add `INVALID` to the enum, but what should the behavior be on the sensor (`ChargerLocked`)? Unknown or unavailable?

**Comment by WebSpider** [comment]
I guess that depends on what the value maps to in reality. @johnvanderster can your car lock the charge cable?

**Comment by johnvanderster** [comment]
Yes, car can lock the charge cable (default = locks)

**Comment by WebSpider** [comment]
I think i encountered this state in real life: my charge cable was locked in the car, and the car could not unlock it.

I think the best translation here is 'Unknown'

**Comment by dvx76** [comment]
Ok so for the `ChargerLockedState` I think we just use the actual value, since it's HA-agnostic. So just `ChargerLockedState.INVALID`.

Then in the `ChargerLocked` ... based on your description above we could use it to have a `is_jammed` property return `True` (see https://developers.home-assistant.io/docs/core/entity/lock), or if we want to mark the entity as temporarily unavailable, I'm not sure what the 'correct' way to do it is? Just have a `available` property return `False` if `ChargerLockedState.INVALID`?

**Comment by WebSpider** [comment]
I like the `is_jammed` 😆

**Comment by dvx76** [comment]
As per [this comment](https://github.com/skodaconnect/myskoda/pull/88#discussion_r1797385502) from Prior99 returning `None` would have HA show the sensor as Unavailable, so that's also an option.
